### ISSUE TITLE
typeahead search suggestions

### ISSUE THREAD

**Issue by Chinese1904** [yclas/yclas#1624]
This used to be a bootstrap component pro BS3. I was thinking about adding this eventually. http://twitter.github.io/typeahead.js/
It would be a nice little feature to get typeahead suggestions for customers, especially with having an API now.

**Comment by neo22s** [comment]
What will this do and where should be?

This will have a huge DB performance impact.  Maybe usage of external tool like https://www.algolia.com/ ? but really expensive.

**Comment by neo22s** [comment]
Find external search providers and integrate one, maybe as said before https://www.algolia.com/

**Comment by oliverds** [comment]
[TNTSearch](https://github.com/teamtnt/tntsearch) seems a good opensource alternative.

**Comment by neo22s** [comment]
@oliverds I prefer external service since will be super heavy for DB. 

Maybe google search ? https://cse.google.com/cse/all
AWS:
https://aws.amazon.com/cloudsearch/
http://www.addsearch.com/

**Comment by oliverds** [comment]
Working on Algolia implementation.

**Comment by neo22s** [comment]
thats good!! better, do they have affiliate program by any chance?

**Comment by oliverds** [comment]
It seems they don't have an affiliate program 👎 .

**Comment by neo22s** [comment]
this looks awesome!!! :D super good!
