### ISSUE TITLE
Put Minion to work

### ISSUE THREAD

**Issue by HurukHai** [yclas/yclas#1860]
Hi, If you're interested in activate Minion(actually isnt working...)

I've done following next steps:
- Fix index.php acordingly the current master branch of Kohana, add something like: 

```
// Bootstrap the application
require APPPATH . 'bootstrap' . EXT;


if (PHP_SAPI == 'cli') // Try and load minion
{
    class_exists('Minion_Task') OR die('Please enable the Minion module for CLI support.');
    set_exception_handler(array('Minion_Exception', 'handler'));
    Minion_Task::factory(Minion_CLI::options())->execute();
} else {
    if ( ! defined('SUPPRESS_REQUEST')) {
        /**
         * Execute the main request. A source of the URI can be passed, eg: $_SERVER['PATH_INFO'].
         * If no source is specified, the URI will be automatically detected.
         */
        echo Request::factory(TRUE, array(), FALSE)
            ->execute()
            ->send_headers()
            ->body();
    }
}
```
- Some bug in Exceptions should be fixed too: 
  .../public/oc/kohana/system/classes/Kohana/Kohana/Exception.php on function handler, change ($e) by (Exception $e)

Y fin.

**Comment by neo22s** [comment]
Hello!

We have something for CLI not as cool but for now was enough.

change ($e) by (Exception $e) --> that was done to be PHP7 compatible ;)

Thanks I will put this in ideas just in case its needed.

Whats your website anunciosenusa?

**Comment by HurukHai** [comment]
Yes, but is not live at all ;-)
