### ISSUE TITLE
Live social auth error

### ISSUE THREAD

**Issue by kotsios5** [yclas/yclas#1993]
Error: please try again! No provider ID specified.

https://github.com/open-classifieds/common/blob/master/vendor/hybridauth/hybridauth/Hybrid/Provider_Adapter.php#L70

**Comment by neo22s** [comment]
When is this happening?

**Comment by kotsios5** [comment]
When I click to login with Live, I get that error. It can be reproduced here: http://kotsios.yclas.com/

**Comment by neo22s** [comment]
aaaaaaaaaaaaaa you mean the provider "Live" hahaha I didnt understand it sorry!! :D

**Comment by neo22s** [comment]
I will take a look.

**Comment by neo22s** [comment]
Did you manage to create the API keys?

the url to create them is https://account.live.com/developers/applications/create

But I get an error:
Your URL can't contain a query string or invalid special characters.

When I need that :S
http://290.dontcode.com/social/login/1?hauth.done=Live

**Comment by neo22s** [comment]
ok... seems live is not working, and not updated since long ago. I will open a issue on the official repo and wait there for an answer.

**Comment by kotsios5** [comment]
Yes, it doesn't allow this character "?". 

I have tried many things but I think the issue is related to the provider ID, as the first error indicates.

**Comment by neo22s** [comment]
no answer from provider yet... I will ask again.

**Comment by oliverds** [comment]
Ok. Checked and tested at http://290.dontcode.com. Now it works.

Redirect URIs must be without the query string. Ex. `http://2181.dontcode.com/social/login/1

<img width="897" alt="screen shot 2016-11-15 at 18 15 04" src="https://cloud.githubusercontent.com/assets/7003648/20329688/74aae814-ab5f-11e6-8710-60f7b76dd6c6.png">
