### ISSUE TITLE
Allow to upload Ads pictures from URL

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2029]
Maybe an option to be able to put a image url as a way of posting and ad?

We will copy the image locally (as base64 in the browser) and then post it?

what do you think @oliverds @kotsios5 ?

maybe as an option in ads settings ;)

**Comment by kotsios5** [comment]
Yes, it would be good to offer this option!

**Comment by oliverds** [comment]
> We will copy the image locally (as base64 in the browser) and then post it?

Using js you mean? I don't think that's possible. The server will need to fetch the image.

**Comment by neo22s** [comment]
we can do 3 things:

- an external API that does this for us
- Or build it inside OC
- or something like this maybe? http://jsfiddle.net/handtrix/YvQ5y/

**Comment by oliverds** [comment]
> something like this maybe? http://jsfiddle.net/handtrix/YvQ5y/

That's what we need. So it's possible to do it. :satisfied:

**Comment by neo22s** [comment]
we will do this in the future
