### ISSUE TITLE
Images uploaded from mobile

### ISSUE THREAD

**Issue by kotsios5** [yclas/yclas#2057]
When you create a new advertisement and upload images from mobile, the images are show in the wrong orientation. When the ad is published the images are displayed fine.

I think we discussed this before but I cannot find any relevant issue.

https://yclas.com/panel/support/ticket/11369

**Comment by oliverds** [comment]
Yep, we fixed it on the server side. Related issue https://github.com/open-classifieds/openclassifieds2/issues/1257

**Comment by neo22s** [comment]
so nothing to fix?

**Comment by oliverds** [comment]
Well it's a bug but it comes from [Jasny Bootstrap](https://github.com/jasny/bootstrap)

**Comment by neo22s** [comment]
ok @kotsios5 explain the customer that seems an issue with an external tool and we have reported it and as soon as its fixed we will also update the package ;)

**Comment by oliverds** [comment]
No news on this bug from Jasny Bootstrap. The latest release is from more than a year ago.

Maybe find alternatives and change plugin?

**Comment by neo22s** [comment]
ok, lets replace it then. 1 year no updates.... bad deal.
