### ISSUE TITLE
VAT for order and EU VAT

### ISSUE THREAD

**Issue by kotsios5** [yclas/yclas#2059]
Add more details about the order or give the ability to use more variables.

Suggestion:
https://yclas.com/forum/support/taxes.html

**Comment by neo22s** [comment]
complicated... we do not have VAT at open classifieds.

Maybe first we should add VAT to orders? like we do in open eshop?

**Comment by kotsios5** [comment]
Maybe that's better, especially if it's required in some countries.

**Comment by kotsios5** [comment]
- [ ] /oc/classes/euvat.php
- [ ] Three options on Settings -> Payment -> General

  a. VAT Number (input)
  b. EU VAT (Enabled/Disabled)
  c. VAT Excluded Countries

- [ ] Calculate final amount with VAT:
		model/order.php
		public function final_price ->  classes/model/ad
		
- [ ] Add field to orders table in DB: 
oc/classes/controller/panel/update.php

DB::query(Database::UPDATE,"ALTER TABLE  `".self::$db_prefix."orders` ADD `VAT_amount`  DECIMAL(14,3) NOT NULL DEFAULT '0' AFTER `VAT`;")->execute();

- [ ] recalculate all orders:
oc/classes/controller/panel/update.php

- [ ] VAT number on profile:
oc/classes/controller/panel/profile.php

- [ ] VAT on email

**Comment by neo22s** [comment]
ok, tomorrow all day testing!

**Comment by neo22s** [comment]
@kotsios5 
2016-11-09 09:19:49 --- ERROR: Kohana_Exception [ 0 ]: The cf_vatnumber property does not exist in the Model_Ad class ~ APPPATH/kohana/modules/orm/classes/Kohana/ORM.php [ 687 ] in /home/opencl7/public_html/2181/oc/kohana/system/classes/Kohana/Kohana/Exception.php:110                

http://2181.dontcode.com/jobs/test.html

updated to 3.0.0

**Comment by neo22s** [comment]
/var/www/yclas/sites/classifieds/www/themes/olson/views/pages/ad/single.php [ 221 ] » Kohana_ORM->__get(arguments)
0	
string(12) "cf_vatnumber"
 
216                                 <td><i class="fa fa-check"></i></td></tr>
217                             <?elseif($value=='checkbox_0'):?>
218                                 <tr><td><strong><?=$name?></strong></td>
219                                 <td><i class="fa fa-times"></i></td></tr>
220                             <?else:?>
221                                 <?if($value != $ad->cf_vatnumber AND $value != $ad->cf_vatcountry):?>
222                                     <tr><td><strong><?=$name?></strong></td>
223                                     <td><?=$value?></td></tr>
224                                 <?endif?>
225                             <?endif?>
226                         <?endforeach?>
