### ISSUE TITLE
S3 Images

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2096]
Review that code on OC does the same as Yclas so there's a clean possible migration. File renaming etc...

Create new option - If S3 is activated, the images not stored in the server disk. 

If you enable s3, a process should be launched to move images from HD to s3. 
if you disable s3,  a process should be launched to move images from s3 to HD.

Maybe something similar to the import tool. And save the status of migration in a config.

related issues:
https://github.com/open-classifieds/openclassifieds2/issues/1730
https://github.com/open-classifieds/openclassifieds2/issues/1713

**Comment by neo22s** [comment]
So theres differences in:

- oc/core.php (s3_upload, s3_domain, imagefly)
- models: ad user category and location (image functions)
- oc/theme.php (upload_image)
- s3oc.php (does not exist)

@oliverds we leave this for 3.0.1 ? I think maybe its too much for right now? or do you have it by the hand?

The import tool I believe I can have in 2/3 hours.

**Comment by oliverds** [comment]
Yep, agree maybe for 3.0.1. I don't think it's that easy to resolve this issue.
