### ISSUE TITLE
Widget search limit categories and locations

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2127]
We need to limit the number of locations or categories in widget search. I think the best will be to load them with the API and limit the output to 200 or similar... if not can get crazy big

**Comment by oliverds** [comment]
There's some complexity on load categories/locations with the API and JS (select2). Also because we have the option to have single select or multiple select.

**Comment by neo22s** [comment]
ok, limiting to 200 should do the work.... ;)
