### ISSUE TITLE
oc3_config empty after install

### ISSUE THREAD

**Issue by kotsios5** [yclas/yclas#2130]
The table oc3_config is empty after install. 

![install-yclassh](https://cloud.githubusercontent.com/assets/11571490/20095735/9c460b72-a59e-11e6-95ad-cdbc3ffa3057.png)

![oc3_config](https://cloud.githubusercontent.com/assets/11571490/20095765/c1a04266-a59e-11e6-8333-a7ac8628d768.png)

**Comment by neo22s** [comment]
damn!

Must be a mysql error on install. let me review it.

needs to be some of the last changes since, I did a install, 1 week ago and was working.
