### ISSUE TITLE
CookieBar issues on different language

### ISSUE THREAD

**Issue by kotsios5** [yclas/yclas#2131]
For example with French:

https://bazdressing.fr
view-source:https://bazdressing.fr/jslocalization/cookieconsent

`$.cookieBar({message: 'Nous utilisons les cookies pour amÃ©liorer l'utilisation du site et enregistrer vos prÃ©fÃ©rences',`

SyntaxError: missing } after property list

**Comment by neo22s** [comment]
please test this good

**Comment by oliverds** [comment]
I'm still having this issue.

I think what we really need is to escape quote strings like for accented words.

**Comment by neo22s** [comment]
aha!! thanks @oliverds for me was working ;)

**Comment by neo22s** [comment]
missing for yclas SaaS no?

**Comment by oliverds** [comment]
PR on its way.
