### ISSUE TITLE
Site stats - Contacts

### ISSUE THREAD

**Issue by kotsios5** [yclas/yclas#2135]
Possible issue with contact stats. After two contacts I checked stats:

By default:
![contact-stats-1](https://cloud.githubusercontent.com/assets/11571490/20113388/2d4ddc6e-a5e8-11e6-949d-d50bdc1d6e65.png)

Changing the "To" date to tomorrow:
![contact-stats](https://cloud.githubusercontent.com/assets/11571490/20113387/2d43c774-a5e8-11e6-8cea-c694b5bc6d7e.png)

**Comment by neo22s** [comment]
I think is because filters to 2016-11-08 00:00:00 so it does not include the entire day ;)

@oliverds correct?

**Comment by oliverds** [comment]
Looks more like a timezone difference between PHP and MySQL because it filters also with a time ex. 2016-11-08 22:36:23.

**Comment by neo22s** [comment]
aha! could be. WE will review this later.
