### ISSUE TITLE
ErrorException - Uncaught Type Error

### ISSUE THREAD

**Issue by kotsios5** [yclas/yclas#2136]
I got this error a few times, it appears on random and it disappears when I refresh the page.

![errr](https://cloud.githubusercontent.com/assets/11571490/20114033/cb4122b2-a5ea-11e6-8916-39f5c8c2fc0d.png)

**Comment by neo22s** [comment]
mmmm weird. thats true.

**Comment by neo22s** [comment]
maybe a cache issue? since when do you see this?

**Comment by kotsios5** [comment]
The last two or three days but I thought it was an issue on local.

**Comment by neo22s** [comment]
happens to any other customer? @oliverds have you experienced this?

**Comment by oliverds** [comment]
I don't have this issue on my local environment.

But yes maybe it's a cache issue.

**Comment by oliverds** [comment]
Ok. Now testing on a Vagrant-Serverpilot environment and starting to get this random error too.

**Comment by neo22s** [comment]
strange since we have not changed anything from the core ... mmmm or the framework. maybe php version?

I am using PHP 7.0.8

**Comment by oliverds** [comment]
Very strange, I'm still not sure what's the problem. Sometimes I get this error and sometimes not.

I'm using PHP 7.0.11.

**Comment by neo22s** [comment]
are you using apcu?

**Comment by oliverds** [comment]
Nop. Just file cache.

**Comment by neo22s** [comment]
try enable apcu and lets see if still happens.

**Comment by oliverds** [comment]
APCu installed and enabled. Still getting sometimes this error.

**Comment by neo22s** [comment]
found the issue!! shit.

Its the freaking exception file.

See commit update and lets see what the error throws.

**Comment by oliverds** [comment]
![screen shot 2016-11-09 at 12 31 06](https://cloud.githubusercontent.com/assets/7003648/20149803/76a91e24-a678-11e6-9d70-12b060a95b37.png)

**Comment by neo22s** [comment]
Strange, seems theres no Request::current().

@oliverds can you edebug it on your local? I can not reproduce it.

**Comment by oliverds** [comment]
Sure. I'm trying to debug it but it's difficult because somehow the error is not always present.

**Comment by neo22s** [comment]
ufff weird.

**Comment by oliverds** [comment]
I don't get it but this error seems to come from classes/cron/update.php calling `OC_Core::get_updates` and it calls `Core::curl_get_contents` but at line https://github.com/open-classifieds/common/blob/master/classes/oc/core.php#L299 `Request::current()` is NULL.

**Comment by neo22s** [comment]
Fuck!! must be this:

https://github.com/open-classifieds/common/blob/4f498f152b58e79310b50f75a68b467f5672eee0/classes/oc/core.php#L299

**Comment by neo22s** [comment]
ok you were faster! hahaha

But if theres an error this should happen https://github.com/open-classifieds/common/blob/master/classes/url.php#L74

strange

**Comment by oliverds** [comment]
> ok you were faster! hahaha
> 
> But if theres an error this should happen https://github.com/open-classifieds/common/blob/master/classes/url.php#L74
> 
> strange

Right! That's the thing I don't get.

**Comment by neo22s** [comment]
check if we can see if Request::current() is initiated or if its null then do the other string. We can putit in a new function like current_php() if theres no current then call current_php if exception same xD

nasty but should work :P
