### ISSUE TITLE
ErrorException [ Notice ]: Undefined offset: 0 APPPATH/classes/model/review.php [ 101 ]

### ISSUE THREAD

**Issue by rviera** [yclas/yclas#2144]
Hello,

I had an issue which I already corrected, however, I'm not sure if you did. 

Version 3.0
Log:
ErrorException [ Notice ]: Undefined offset: 0
APPPATH/classes/model/review.php [ 101 ]

I replaced:
return $rates[0]['rate'];
for:
return (isset($rates[0]))?round($rates[0]['rate'],2):FALSE;

Hope it helps.

PS: I'm sorry if I'm not allowed to post here. Is there another way to post issues/solutions now that the oc forum is closed? I have many to share with you ;)

**Comment by neo22s** [comment]
thanks!
