### ISSUE TITLE
Change eu vat api

### ISSUE THREAD

**Issue by kotsios5** [yclas/yclas#2153]
https://github.com/yclas/yclas/issues/2059

Use https://github.com/neo22s/euvat/blob/master/app/euvat.php instead of https://github.com/yclas/yclas/blob/master/oc/classes/euvat.php

**Comment by neo22s** [comment]
You mean usage of https://euvat.ga/ ?

The issue is that if one day the api is down will not work....

**Comment by kotsios5** [comment]
I mean to use the code of that file, not the external API. It works the same with the current one, not sure if it's necessary to change it :/

**Comment by neo22s** [comment]
I tihnk code is mostly the same hehe review please.

**Comment by kotsios5** [comment]
It works the same, code is mostly the same. There's no need to change it.
