### ISSUE TITLE
S3 amazon

### ISSUE THREAD

**Issue by hrncir39** [yclas/yclas#2157]
Hello, 

Will be ready amazon s3 in 3.0.1 and new relase and can i purche 1 license for my own server?

Thanks and good work

**Comment by neo22s** [comment]
Hello!

Here https://github.com/yclas/yclas/issues/2096 ;)

But yes we do have s3 already and if you buy you get updates ;)

**Comment by hrncir39** [comment]
If possible buy 1 license for my one website per 60$ so ok :) 
Thans for res.

**Comment by hrncir39** [comment]
If possible buy 1 license for my one website per 60$ so ok :)
Thans for res.
