### ISSUE TITLE
Import CSV categories

### ISSUE THREAD

**Issue by tiborman** [yclas/yclas#2158]
I ran into a problem when importing categories. Example: I have 2 category (coins and notes) and you should have subcategories that match the name. When you import will import only the first major category to the other, will not import anything. The system because they think that those categories already exist. I need to do but the same category, but systemically with a different ID. Is it somehow possible? Thank you, sorry for bad English...

**Comment by neo22s** [comment]
Hello,

This is not a support forum, its only for developers, did you find an error in the source code?

Please for support of usage  use the correct place. https://docs.yclas.com/ or contact us https://yclas.com/contact.html or buy support https://selfhosted.yclas.com/support/

thanks a lot!

**Comment by tiborman** [comment]
Hi, thanks, I find error when i work on yclas with this issue. I dont need support. Thanks a lot
