### ISSUE TITLE
Upload files to ads

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2159]
We will not allow to upload huge files... we are going to play it smart ;)

Dropbox / Drive custom field type - https://www.dropbox.com/developers/chooser - https://developers.google.com/picker/

:dancer: 

if its an item on sale, the download link will not appear and its added on the seller email ;)

**Comment by oliverds** [comment]
- [x] Dropbox Chooser
- [ ] Google Picker

**Comment by oliverds** [comment]
Google Picker, Can't make work yet. Seems more complex its implementation.

**Comment by oliverds** [comment]
**How it works with Dropbox**

1. Create a new app on the Dropbox Platform (https://www.dropbox.com/developers/apps/create)
2. Set app key on Setting->Advertisement->Dropbox->App key
3. New custom field **File** on Classifieds->Custom fields
4. Done.

To use a **File** custom field as the download link on item sale the custom field name **must be** `file_download` and the download link will be added as buyer instruction on the seller email (https://github.com/oliverds/openclassifieds2/commit/b30cad647b821f6e0017fb5949d9e6939b90a41c#diff-dafea07a6df9e8bf7e66ef957fa63994R1031).

**Comment by neo22s** [comment]
This looks great!! super useful damn!!

Now we need to appear a Download button instead of the string.

If google takes too long we put it in a different issue and we do it int he future. By having dropbox.... we cover a lot already, what do you think @oliverds  ??

**Comment by neo22s** [comment]
https://github.com/oliverds/openclassifieds2/commit/b30cad647b821f6e0017fb5949d9e6939b90a41c#diff-dafea07a6df9e8bf7e66ef957fa63994R1031

here we can attach the link in case they have both

$buyer_instructions .= $this->cf_file_download;

Will be better, what you think?

**Comment by oliverds** [comment]
Yeah. Love this feature.

> Now we need to appear a Download button instead of the string.

Agree!

> If google takes too long we put it in a different issue and we do it int he future. By having dropbox.... we cover a lot already, what do you think @oliverds ??

Ok. Moving Google Picker integration to another issue

> $buyer_instructions .= $this->cf_file_download;

Absolutely right, my bad. Should be concatenated.
