### ISSUE TITLE
BUG - php-gettext. 

### ISSUE THREAD

**Issue by hrncir39** [yclas/yclas#2163]
I have setting setlocale in mac OS X. Do you know how to fix? 

Warning: include(/Users/Jakub/Projects/www/class.dev/oc/common/vendor/php-gettext/gettext.inc): failed to open stream: No such file or directory in /Users/Jakub/Projects/www/class.dev/install/class.install.php on line 286

Warning: include(): Failed opening '/Users/Jakub/Projects/www/class.dev/oc/common/vendor/php-gettext/gettext.inc' for inclusion (include_path='.:/Applications/MAMP/bin/php/php7.0.8/lib/php') in /Users/Jakub/Projects/www/class.dev/install/class.install.php on line 286

Fatal error: Uncaught Error: Call to undefined function T_setlocale() in /Users/Jakub/Projects/www/class.dev/install/class.install.php:288 Stack trace: #0 /Users/Jakub/Projects/www/class.dev/install/class.install.php(74): install::gettext_init('cs_CS') #1 /Users/Jakub/Projects/www/class.dev/install/index.php(32): install::initialize() #2 /Users/Jakub/Projects/www/class.dev/index.php(116): include('/Users/Jakub/Pr...') #3 {main} thrown in /Users/Jakub/Projects/www/class.dev/install/class.install.php on line 288

**Comment by neo22s** [comment]
Hello,

This is not a support center, is for developers contributing in the project.

Please review the guidelines for contributing to this repository.

https://github.com/yclas/yclas/blob/master/CONTRIBUTING.md

If you need support please see our docs
https://docs.yclas.com/
https://docs.yclas.com/install-self-hosted/
https://docs.yclas.com/how-to-develop-local/
https://docs.yclas.com/docker-image/
https://docs.yclas.com/vagrant-configuration/

regards
