### ISSUE TITLE
erreur after update

### ISSUE THREAD

**Issue by roufa2016** [yclas/yclas#2164]
after update from 2.9 to 3.0.. i get thiserreur inoplanel when i wanna display classfields
![1](https://cloud.githubusercontent.com/assets/24283466/20778385/25c6e67a-b722-11e6-95f3-8024e66ade6f.jpg)

**Comment by neo22s** [comment]
Hello,

This is not a support center, is for developers contributing to the project.

Please review the guidelines for contributing to this repository.
https://github.com/yclas/yclas/blob/master/CONTRIBUTING.md

If you need support please see our docs
https://docs.yclas.com/
https://docs.yclas.com/how-to-update/

or check our support packs
https://selfhosted.yclas.com/support

regards
