### ISSUE TITLE
Upload Files to Ads with Google Picker

### ISSUE THREAD

**Issue by oliverds** [yclas/yclas#2168]
Similar to https://github.com/yclas/yclas/issues/2159 but with [Google Picker](https://developers.google.com/picker/) implementation.

**Comment by neo22s** [comment]
can we do a bit of documentation so we can test and @kotsios5 can do the docs? thanks!!!

**Comment by oliverds** [comment]
Sure. Doing some screenshots. The Google API part is a bit tricky.

**Comment by neo22s** [comment]
Yes... google api and FB api sucks.... then you see stripe or dropbox and
is sooo simple...

Chema Garrido
*Barcelona Developer*
e: chema@garridodiaz.com
w:chema.ga

**Comment by oliverds** [comment]
Hahaha but yes so much complication with Google and Facebook API configuration.

**Comment by oliverds** [comment]
How to get the required Google Picker API Key and Google Picker Client ID

1. https://console.developers.google.com
2. Create a new project
<img width="830" alt="screen shot 2016-12-20 at 14 54 42" src="https://cloud.githubusercontent.com/assets/7003648/21367907/a9140910-c6c5-11e6-9304-20ff71b065b4.png">
3. Create credential
<img width="834" alt="screen shot 2016-12-20 at 14 55 18" src="https://cloud.githubusercontent.com/assets/7003648/21367912/b1642dca-c6c5-11e6-8971-109d9ed7028c.png">
4. Select API Key
<img width="836" alt="screen shot 2016-12-20 at 14 55 25" src="https://cloud.githubusercontent.com/assets/7003648/21367928/c1f32efc-c6c5-11e6-9753-c02ee6a64272.png">
5. This is the Google Picker API Key to enter at https://reoc.lo/oc-panel/settings/form (tab Google picker)
<img width="826" alt="screen shot 2016-12-20 at 14 55 36" src="https://cloud.githubusercontent.com/assets/7003648/21367943/ceb72ed6-c6c5-11e6-9529-0de64727bb50.png">
6. Create credential
<img width="834" alt="screen shot 2016-12-20 at 14 55 18" src="https://cloud.githubusercontent.com/assets/7003648/21367912/b1642dca-c6c5-11e6-8971-109d9ed7028c.png">
7. Select Create Client ID
8. Configure Concent 
<img width="904" alt="screen shot 2016-12-20 at 14 55 56" src="https://cloud.githubusercontent.com/assets/7003648/21367953/df00bdac-c6c5-11e6-898e-01b52baa058a.png">
<img width="891" alt="screen shot 2016-12-20 at 14 56 38" src="https://cloud.githubusercontent.com/assets/7003648/21368017/13ace8e6-c6c6-11e6-97af-40d98f9ca736.png">
9. Create Client ID
<img width="888" alt="screen shot 2016-12-20 at 14 56 48" src="https://cloud.githubusercontent.com/assets/7003648/21368030/26f17944-c6c6-11e6-9f24-89e1361e90bf.png">
10. This is the Google Picker Client ID  to enter at https://reoc.lo/oc-panel/settings/form (tab Google picker)
<img width="894" alt="screen shot 2016-12-20 at 14 56 58" src="https://cloud.githubusercontent.com/assets/7003648/21368031/2dd29c98-c6c6-11e6-8bb4-02c9d61866d0.png">
11. To enable Google Picker API

11. a. Find and select "Google Picker" <img width="894" alt="screen shot 2016-12-20 at 14 57 09" src="https://cloud.githubusercontent.com/assets/7003648/21368070/60b6d570-c6c6-11e6-9442-f939f25fbbf1.png">
12. b. Button enable
<img width="906" alt="screen shot 2016-12-20 at 14 57 17" src="https://cloud.githubusercontent.com/assets/7003648/21368085/78a855fa-c6c6-11e6-908b-67960cc332cf.png">

**Comment by neo22s** [comment]
OMG hahahha
