### ISSUE TITLE
Unable to print orders

### ISSUE THREAD

**Issue by oliverds** [yclas/yclas#2171]
At line https://github.com/yclas/yclas/blob/master/themes/default/js/oc-panel/order.js#L2 we find the `#print` content on a div tag but we don't have any at https://github.com/yclas/yclas/blob/master/themes/default/views/oc-panel/profile/order.php

**Comment by oliverds** [comment]
That was fast @kotsios5 👍 

I just added bootstrap so the print view can look better.

**Comment by kotsios5** [comment]
@oliverds Great! Looks much better now!
