### ISSUE TITLE
PHP Issue - Probably

### ISSUE THREAD

**Issue by mmcduffie1** [yclas/yclas#2175]
I am 99% sure I installed any requirements. But due to other software on my server, I am running php7.0 with apache2. The yclas git is in the right place. All things are right with the world, then this message when I opened my browser to install:

`Warning: include(/var/www/html/yclas/oc/common/vendor/php-gettext/gettext.inc): failed to open stream: No such file or directory in /var/www/html/yclas/install/class.install.php on line 286

Warning: include(): Failed opening '/var/www/html/yclas/oc/common/vendor/php-gettext/gettext.inc' for inclusion (include_path='.:/usr/share/php') in /var/www/html/yclas/install/class.install.php on line 286

Fatal error: Uncaught Error: Call to undefined function T_setlocale() in /var/www/html/yclas/install/class.install.php:288 Stack trace: #0 /var/www/html/yclas/install/class.install.php(74): install::gettext_init('en_us') #1 /var/www/html/yclas/install/index.php(32): install::initialize() #2 /var/www/html/yclas/index.php(116): include('/var/www/html/y...') #3 {main} thrown in /var/www/html/yclas/install/class.install.php on line 288`

What am I missing here or is it the php7?

**Comment by neo22s** [comment]
Hello,

It's a permissions issue. Not related with PHP7, we are compatible up to 7.1.

For installation instructions:
https://docs.yclas.com/install-self-hosted/
https://docs.yclas.com/digital-ocean-vultr-linode
https://docs.yclas.com/requirements-yclas-self-hosted

If you need a compatible hosting:
https://docs.yclas.com/yclas-hosting/

But please this is not a support place, it is for fixing development issues. see https://github.com/yclas/yclas/blob/master/CONTRIBUTING.md

regards! ;)
