### ISSUE TITLE
PHP 7.1: Deprecated Mcrypt

### ISSUE THREAD

**Issue by oliverds** [yclas/yclas#2176]
Starting from PHP 7.1 all mcrypt_* functions are raising an E_DEPRECATED notice and for PHP 7.2 or PHP 8.0 will be removed.

So we should no longer use `Kohana_Encrypt` class.

Reference:
https://wiki.php.net/rfc/mcrypt-viking-funeral

**Comment by neo22s** [comment]
I am well aware, the issue is that we use that library to encrypt and decrypt so current passwords on DB will not work all the QL's etc...

I saw forums where they mention to fork it and keeping it alive, lets see... thats for 8.0 heheh

**Comment by neo22s** [comment]
We have a new encrypt module.

https://github.com/koseven/koseven/tree/devel/modules/encrypt

See compatibility. and how this affects currently stored passwords.

**Comment by neo22s** [comment]
ok, much simpler than I thought.

We actually use http://php.net/manual/en/function.hash-hmac.php for the passwords in the DB, I was wrong.

We use the Encrypt class for email (unsubscribe) and to generate the QL.

So we can modify the encrypt.php config to use openssl.

**Comment by neo22s** [comment]
https://github.com/koseven/koseven/issues/99#issuecomment-302802685

**Comment by neo22s** [comment]
@oliverds @kotsios5 we need to test this really good!
