### ISSUE TITLE
Catpcha issues when registering

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2177]
we disable captcha does not appear on register and form submit fails.

**Comment by oliverds** [comment]
Very strange. Cannot reproduce this issue on local, reoc.lo or yclas.lo.

Everything looks fine.

If config advertisement.captcha is not enabled, Captcha::check() returns true (https://github.com/open-classifieds/common/blob/5df7e7c97a9a129dd089b73b7104105caa16c0c8/classes/oc/captcha.php#L88) and we don't display input on register form (https://github.com/open-classifieds/common/blob/5df7e7c97a9a129dd089b73b7104105caa16c0c8/views/pages/auth/register-form.php#L56).

**Comment by oliverds** [comment]
No issues on yclas.tk either.

@neo22s Could be somehow a server config issue on yclas.com?

**Comment by neo22s** [comment]
happens in any other yclas.com site? yes could be a config but a really strange one xD

**Comment by oliverds** [comment]
Yes, at http://mexico.yclas.com/oc-panel/auth/login

**Comment by neo22s** [comment]
wow shit hahaha

**Comment by neo22s** [comment]
asking the sys admin guy

**Comment by oliverds** [comment]
Was a server issue.
