### ISSUE TITLE
Improve home page load

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2181]
When loading the categories the see more link will load categories using AJAX and our API.

What if it opens a modal with the categories?

**Comment by oliverds** [comment]
Yes, like showing up to the first 15-20 subcategories and later display all with a modal.

**Comment by neo22s** [comment]
Looks good! maybe implemtn same in other themes like olson? better in all of them... smooth

**Comment by oliverds** [comment]
Oops. Right! Olson theme was missing.

**Comment by oliverds** [comment]
Not implemented in Yummo, Pinclass & Jobdrop because we don't display categories in home view on those themes.
