### ISSUE TITLE
API Image Upload not working

### ISSUE THREAD

**Issue by rikeshrajbangshi** [yclas/yclas#2187]
Hello,

I need Help, I can't upload image through API through iOS. We have a license also.

Purchase order ID : 3578

let adpublishphotosUrl = NSURL(string: API_URL + "ads/image/1")    
let request = NSMutableURLRequest(URL: adpublishphotosUrl!) 
request.HTTPMethod = "POST"  
let postString = "apikey=(API_KEY)&user_token=(UserToken)&image=(img123.image)"  
request.HTTPBody = postString.dataUsingEncoding(NSUTF8StringEncoding)

API_URL = "http://vintecincopt.com/api/v1/"
API_KEY = "z2mr4q@********************"
UserToken = "cd69b161bc48e6804e45b39bcc028b5761f065b6"

We get "Advertisement no found" error,  while ad_id 1 exists.

**Comment by neo22s** [comment]
Hello,

This is not a support forum.

Please open a ticket. https://selfhosted.yclas.com/oc-panel/support/new since you have private support there available.

regards
