### ISSUE TITLE
Register better UX

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2201]
In all themes

![image](https://cloud.githubusercontent.com/assets/241725/21381670/03f6e040-c75d-11e6-94a4-2cc83b2e98c2.png)

Already Have an Account? Login (this is a simple text with a link not a button)

**Comment by neo22s** [comment]
Looks much better!!!

Now the issue is that when you are in /oc-panel/auth/register nor the strength indicator or the captcha refresh works.

**Comment by oliverds** [comment]
Right!

The issue is that we are displaying two register forms, in the modal and in main content. I'm checking it.
