### ISSUE TITLE
The cf_file_download property does not exist in the Model_Ad class 

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2202]
If you have a CF type file and is not called cf_file_download we get a crash.

Possible solutions:

1. we just allow any name
2. check if isset

![image](https://cloud.githubusercontent.com/assets/241725/21384330/67ceb55e-c76a-11e6-963b-5ecb6214dc16.png)

**Comment by oliverds** [comment]
My bad!

At line https://github.com/yclas/yclas/blob/master/oc/classes/model/ad.php#L920 should be `$cf_value = '<a'.HTML::attributes(['class' => 'btn btn-success', 'href' => $cf_value]).'>'.__('Download').'</a>';`
