### ISSUE TITLE
Dropbox and Drive at same time

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2205]
Can be the 2 of them enabled at same time?

**Comment by oliverds** [comment]
Not currently.

Not sure if it's the best to have both services at the same time but can be done by having two different *file* custom fields, like *dropbox_file* and *gdrive_file*.

**Comment by neo22s** [comment]
ups... :S maybe we can let them choose? the one who will post? 

I mean its to offer both options, dropbox or drive.

Please check it ;)

**Comment by neo22s** [comment]
Missing at Yclas.com ?

**Comment by neo22s** [comment]
I also meant like having both activated at same time in the publish new xD

**Comment by neo22s** [comment]
@oliverds but with this new code if we had a custom field of type file? would be lost? I can not upload it since will break the sites that are using custom field "file"

**Comment by neo22s** [comment]
@oliverds we need to modify also the docs, right?

**Comment by neo22s** [comment]
@oliverds but still this will allow to have 2 custom fields called differently but you can not have a unique custom field "file_download" that can choose Dropbox or Drive.

**Comment by neo22s** [comment]
Adding
` case 'file_dropbox':`
here
https://github.com/yclas/yclas/blob/master/oc/classes/model/ad.php#L919

And in the new.js files the same.

Will fix the problem for people that had this type of custom field before, right?

**Comment by oliverds** [comment]
i.e You can have multiple `file` type custom fields but only one can be a download link for after purchase.
