### ISSUE TITLE
Update all vendor scripts

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2216]
I will take care of the PHP vendors

@oliverds review all the JS and CSS

**Comment by neo22s** [comment]
**Updated**

- PHPMailer https://github.com/PHPMailer/PHPMailer
- Mobile Detect https://github.com/serbanghita/Mobile-Detect
- amazon-s3-php-class https://github.com/tpyo/amazon-s3-php-class
- AuthorizeNet https://github.com/AuthorizeNet/sdk-php/
- Hybrid Auth https://github.com/hybridauth/hybridauth
- jsmin-php https://github.com/rgrove/jsmin-php/ (but not updated since 3 years ago)
- Stripe https://github.com/stripe/stripe-php
- GCM-PHP-Server-Push-Message https://github.com/mattg888/GCM-PHP-Server-Push-Message
- GoogleAuthenticator https://github.com/PHPGangsta/GoogleAuthenticator

**Not updated, they seem discontinued**

- DomainParser https://github.com/novutec/DomainParser/
- File_Gettext http://pear.php.net/package/File_Gettext --> https://github.com/pear/File_Gettext
- POTCreator https://github.com/neo22s/potcreator
- php5-akismet https://github.com/achingbrain/php5-akismet
- PHP-Gettext https://github.com/neo22s/php-gettext
- PHP.mo https://github.com/josscrowcroft/php.mo
- PHP-SitemapGenerator https://github.com/pawelantczak/php-sitemap-generator

**Not updated in latest version**

- codebird-php https://github.com/jublonet/codebird-php
- MercadoPago https://github.com/mercadopago/sdk-php
- Minify https://github.com/mrclay/minify
- FraudLabsPro https://github.com/neo22s/fraudlasbspro

**Comment by oliverds** [comment]
# JS + CC

## Updated
Bootstrap -> 3.3.7
Font Awesome -> 4.7.0
Blueimp-gallery -> 2.15.0
Select2 -> 4.0.3
Jquery -> 1.12.4
Jquery validation -> 1.15.0
Holder -> 2.9.3

## Deprecated
Bootstrap.image-gallery

## Abandoned
Bootstrap.datepicker

**Comment by neo22s** [comment]
I am wondering what to do.

The deprecated we need to find substitution or will always work?

Abandoned, can we clone it or find alternative?

I will consider same with PHP.

**Comment by oliverds** [comment]
Not always will work so I will find alternatives for those scripts while I'm working on https://github.com/openclassifieds/yclas/issues/1157
