### ISSUE TITLE
Improve tests

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2218]
Be sure that tests covers as much and as many options as we can ;)

Automate before deployment? we need to check if theres a way to automate codeception after doing a commit? to see if the commit broke anything?

similar to what this does
https://travis-ci.org/

**Comment by kotsios5** [comment]
working on https://travis-ci.org/kotsios5/yclas-test and https://github.com/kotsios5/yclas-test/

**Comment by neo22s** [comment]
Is this done?

**Comment by kotsios5** [comment]
@neo22s Not yet, few things left.

**Comment by neo22s** [comment]
this is working no? should I move it to travis-ci.org

**Comment by kotsios5** [comment]
Yes, it works. I am still working on the issue creating more tests to cover more options. What do you mean to move it to travis-ci.org?

**Comment by neo22s** [comment]
to add it on travis I mean with our account, or its already in there?

**Comment by kotsios5** [comment]
it's not there yet, now it's ready to add it. It only needs to be enabled here: https://travis-ci.org/profile/yclas
