### ISSUE TITLE
Related ads

### ISSUE THREAD

**Issue by kotsios5** [yclas/yclas#2220]
People asked for this a couple of times lately, it seems they prefer to have related ads of the same category AND location. Currently the related ads are ads from the same category OR location.

https://github.com/yclas/yclas/blob/master/oc/classes/model/ad.php#L969-L970

**Comment by oliverds** [comment]
Perhaps we can create a new config so users can choose how to find related ads. "Category AND Location" or "Category OR Location".

**Comment by neo22s** [comment]
And if we do always:

"Category AND Location" 

And only if nothing is found:

"Category OR Location"

?
