### ISSUE TITLE
Review widget categories

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2225]
https://yclas.com/forum/suggestions/problemas-widget-categorias.html

This is something I thing we had before... let's test it.

**Comment by oliverds** [comment]
Issue reproduced. It seems similar to https://github.com/yclas/yclas/issues/952.

**Comment by oliverds** [comment]
Ok. Problem was the cache name generated at line https://github.com/open-classifieds/common/blob/master/classes/oc/view.php#L58 with method `URL::current()`.
