### ISSUE TITLE
Auto Post Instagram, Pinterest

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2229]
Instagram https://github.com/mgp25/Instagram-API/wiki#upload-photo-and-video

pinterest https://github.com/dirkgroenen/Pinterest-API-PHP#create-pin

**Comment by neo22s** [comment]
Error posting on instagram
InstagramAPI\LoginResponse : checkpoint_required

![image](https://cloud.githubusercontent.com/assets/241725/22616771/0fb6312c-eab4-11e6-86ef-9a27ff5c83e8.png)


We should do a try catch and log it but never show an error

**Comment by neo22s** [comment]
ok, seems the user needs to accept it in the app, we sohuld catch that error anyway.

**Comment by neo22s** [comment]
so only pinterest missing right?

**Comment by kotsios5** [comment]
@neo22s yes!
