### ISSUE TITLE
Shipping fee

### ISSUE THREAD

**Issue by kotsios5** [yclas/yclas#2231]
Seller can choose if buyer can select between delivery (price with shipping) or pick up the product (price without shipping).

https://yclas.com/panel/support/ticket/16135

**Comment by neo22s** [comment]
in the checkout page, no? mmm that should be an option for each ad, or global config?

its a good idea.

**Comment by kotsios5** [comment]
I think it would be better to have this option for each ad. In the checkout page, or if the option is enabled we can show the Buy Now button as a dropdown menu with the options Collection and Delivery, if it's not complicated.
