### ISSUE TITLE
Blog page preview

### ISSUE THREAD

**Issue by kotsios5** [yclas/yclas#2239]
In the page /blog we show only the first 255 characters of each blog post. In cases that they have only images it shows all the content since the code of the images has no many characters.

Example: http://gamersclassified.com/blog

**Comment by neo22s** [comment]
so whats the solution? remove all html?

**Comment by kotsios5** [comment]
Reducing the number of characters won't make it any better, so removing the html sounds the best solution.

**Comment by neo22s** [comment]
ok, we have a function for that to remove html.

https://github.com/yclas/yclas/blob/master/oc/common/classes/oc/text.php#L162

or strip_tags and then
https://github.com/yclas/yclas/blob/master/oc/kohana/system/classes/Kohana/Text.php#L90
