### ISSUE TITLE
Maps with only nearby ads

### ISSUE THREAD

**Issue by Cyberdejy** [yclas/yclas#2249]
Is it possible to place a widget or html code in the header or body who is showing only nearby ads?
I mean if I have ads in London and Manchester and the user is from London the browser should ask for the user location and hide the ads from Manchester.
I know that under LISTING there is a button for distance where the user can choose a distance based on his/her post code or address but I want this to be automaticaly.

Thank you

**Comment by neo22s** [comment]
Hello,

Please this is not a support forum, this is meant for developers.

If you have any question you can contact us directly.

thanks
