### ISSUE TITLE
"An error :'(" after installation

### ISSUE THREAD

**Issue by dagonzaros** [yclas/yclas#2257]
I go through the installation script and then it redirects me to the error page... I have no clue where to move forward from here, tried completely reinstalling, same issue.

**Comment by dagonzaros** [comment]
After further review, I'm seeing a "PHP Fatal error: 'OC_Database_Query' not found in ~/oc/classes/database/query.php on line 3"

**Comment by neo22s** [comment]
Hello,

Please this is not a support forum. Os for developers.

If you need support you can just open a ticket or contact us directly by email. We will help you there.

Thanks

**Comment by dagonzaros** [comment]
Hi, what is your email?

**Comment by neo22s** [comment]
http://yclas.com/

**Comment by dagonzaros** [comment]
Hi, I attempted opening a support ticket and it tells me that I have to use the forums, the forums are 'disabled' and you won't give me support here or an email. How am I supposed to want to buy your product if I can't even get help?

**Comment by neo22s** [comment]
You need to contact us here https://yclas.com/contact.html

If you can not install we recommend you using yclas.com which does not require any technical requirements and you can start for free.

regards
