### ISSUE TITLE
Import categories with the same name

### ISSUE THREAD

**Issue by kotsios5** [yclas/yclas#2263]
If users try to import categories and they have categories with the same name but different parent category, it imports only the first category with that name.

In the example below, it imported only the first "other ..." category:

![other-categories](https://cloud.githubusercontent.com/assets/11571490/22981883/6c73185a-f395-11e6-989e-2b4582b0e541.JPG)

**Comment by neo22s** [comment]
let know the client that he should not have many categories anyway ;)
