### ISSUE TITLE
Replacement for hybridauth

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2264]
Theres so so so so so many issues with this horrible library...

Lets find an alternative to https://github.com/hybridauth/hybridauth that is updated and actually works...

**Comment by neo22s** [comment]
https://github.com/thephpleague/oauth2-client
https://github.com/thephpleague/oauth2-client/blob/master/docs/providers/league.md
https://github.com/thephpleague/oauth2-client/blob/master/docs/providers/thirdparty.md

outdated
https://github.com/opauth/opauth

For laravel great
https://github.com/laravel/socialite
https://socialiteproviders.github.io/

We can always implement each individually... :(

**Comment by cybernet** [comment]
what exactly do you need ?
same thing that HybridAuth offered ?

**Comment by neo22s** [comment]
yep ;)

**Comment by neo22s** [comment]
seems to be working fine... for now.
