### ISSUE TITLE
Delete cache selectively

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2265]
We use a lot Core::delete_cache();, which deletes all the cache of all the site 

This a big issue, since expires all the other keys... when theres no need... for example when saving categories, locations, content etc...

What we will need to do in this cases is to create a method delete_cache() for each model. Then inside this methods invalidate only those keys that are related to the change.

Example
https://github.com/yclas/yclas/blob/master/oc/classes/controller/panel/category.php#L80

Should be something like Model_Config::delete_cache();

This method will clean related keys like 
https://github.com/yclas/yclas/blob/master/oc/classes/model/category.php#L219
To clean simply set to NULL Core::cache('cats_parent_deep', NULL);

I know is a huge task but this will improve the load of sites and save a lot of DB queries.... really a lot.

And we could increase the cache expire time to a lot more like 24 hours since we invalidate by key.

Regarding cache queries... maybe we need to avoid them and query outside so we know the name of the key.

**Comment by oliverds** [comment]
A problem I see is how to clean the cache from dynamic names like https://github.com/yclas/yclas/blob/master/oc/classes/model/category.php#L250?

**Comment by neo22s** [comment]
Yes indeed lets work on the home page builder and we discuss this one later
;)

**Comment by neo22s** [comment]
its taking lot of time.... since I have rewritten it.

But basically what I am doing is that the ORM will know what has been cached no matter the Model_ and will be deleted on demand or on create/update/delete.

Much better :D
