### ISSUE TITLE
Subscription system renewal

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2272]
Option if not renewed all the ads and the profile goes offline.

**Comment by neo22s** [comment]
We can create setting on ads or general, that says "Subscription Expires", and have some options:
1 - Do nothing (like now)
2 - Expire ads and disable profile

For case 2:
In https://github.com/yclas/yclas/blob/master/oc/classes/cron/subscription.php#L91 we need to make a update query (do not loop the ads)

```
DB::update('ads')->set(array('status' =>Model_Ad::STATUS_UNAVAILABLE ))->where('id_user', '=',$user->id_user)->where('status', '=',Model_Ad::STATUS_PUBLISHED)->execute();
```

set status to Model_Ad::STATUS_UNAVAILABLE and user to STATUS_EXPIRED (new status). and will not be displayed in https://github.com/yclas/yclas/blob/master/oc/classes/controller/user.php#L26 anymore.

Then in https://github.com/yclas/yclas/blob/master/oc/classes/model/subscription.php#L71
Reenable ads with STATUS_UNAVAILABLE and set user STATUS_EXPIRED to STATUS_ACTIVE

```
DB::update('ads')->set(array('status' =>Model_Ad::STATUS_PUBLISHED ))->where('id_user', '=',$user->id_user)->where('status', '=',Model_Ad::STATUS_UNAVAILABLE)->execute();
```

Can be done without much issues. My only worry right now is how to call this new setting. Or should be the default behaviour? @kotsios5 @oliverds

**Comment by kotsios5** [comment]
In my opinion case 2 shouldn't be the default behavior, an option would be the best. "Subscription Expires" sounds good, a help-block below the option would explain that better.

**Comment by neo22s** [comment]
Where can we put this setting? in ads? or in general? theres going to be a bit of confusion.

**Comment by neo22s** [comment]
and should appear only if subscription plugin is enabled...

**Comment by oliverds** [comment]
As a setting sounds good.

To me seems better a new subscription action in settings even if it's the only setting.

**Comment by neo22s** [comment]
we will enable it by default, add it to additional features and explain in docs how to disable it.

Now testing, but is such a mess god haah

**Comment by neo22s** [comment]
I can not change the status of the user... or he will not be able to login on his site :S damn

**Comment by neo22s** [comment]
also I need to add controls so they can not reactivate an ad... ufff hahaha
