### ISSUE TITLE
APi error

### ISSUE THREAD

**Issue by cybernet** [yclas/yclas#2281]
i'm using 3.1.0 and when trying to access **/api/v1/customfields/users**?apikey=XXX

i get

Since you are loged in as admin only you can see this message:

Call to undefined method Controller_Api_Customfields::error()
It's been loged in Panel->Tools->Logs for more information regarding this error.

**Comment by cybernet** [comment]
and it wasn't logged :)

**Comment by cybernet** [comment]
https://docs.yclas.com/api-documentation/#custom-fields-users

needs to be fixed, as it shows /api/v1/customfields/**users** instead of **user**

**Comment by neo22s** [comment]
fixed https://github.com/yclas/documentation/commit/96def998b5db3caeba8120b8df23a5b0c02802eb
