### ISSUE TITLE
Internal server error when installing with Docker

### ISSUE THREAD

**Issue by juanpastas** [yclas/yclas#2316]
I followed https://github.com/yclas/docker.

My docker container is running and accessible through port 80.

Installation wen through and then I got internal server error. Reviewing apache logs gave a redirection loop:

```
[Wed Mar 22 00:39:15.280088 2017] [core:error] [pid 624] [client 182.53.192.128:60200] AH00124: Request exceeded the limit of 10 internal redirects due to probable configuration error. Use 'LimitInternalRecursion' to increase the limit if necessary. Use 'LogLevel debug' to get a backtrace.
```

I will try later with debug log level. I had to `cp install-yclas.php /var/www/html` inside container so that I could access it.

**Comment by neo22s** [comment]
Please use https://github.com/yclas/docker/issues thanks
