### ISSUE TITLE
Email templates status

### ISSUE THREAD

**Issue by kotsios5** [yclas/yclas#2326]
Email template status is set to 0 but the email is sent.

**Comment by oliverds** [comment]
Ok. It seems we are not checking the content status on https://github.com/yclas/yclas/blob/master/oc/classes/model/content.php#L103

**Comment by neo22s** [comment]
this happens only if you are admin or moderator. as I can see in the code.

We need to review this.

@kotsios5 just tell the customer to try with a normal user and email wont be sent ;)
