### ISSUE TITLE
Design is not responsive 

### ISSUE THREAD

**Issue by rakaraka** [yclas/yclas#2338]
Hi all,
installed it and was very disappointed when i found out that design is not responsive.
has anyone worked on it ?

**Comment by neo22s** [comment]
Free version is not responsive. PRO version it is and comes with 14 themes https://selfhosted.yclas.com/

If you want to try for free check https://yclas.com/

**Comment by rakaraka** [comment]
thanks..
so this is free version and it will allow me to post only 5 advertisements ? can i host and post unlimimited ads ?

**Comment by neo22s** [comment]
please this is github is for developers as we indicate before opening and issue. any question you may have you can contact from https://yclas.com/ and the correct person will answer to you.
