### ISSUE TITLE
No user email on subscriptions

### ISSUE THREAD

**Issue by kotsios5** [yclas/yclas#2346]
Some subscriptions has the user email field empty, the orders of those subscriptions has no user email too. I couldn't reproduce it on local yet, it happens on https://brassandarrows.ca/oc-panel/order/index

https://yclas.com/panel/support/ticket/22233

**Comment by neo22s** [comment]
Those are users deleted from the DB.

how to reproduce it.
1- create a user
2- pay anything, this will create an order
3- From admin delete the user
4- then you get an order without email since theres no user ;)

Resuming: orders are not deleted if user is deleted, on purpose ;)

**Comment by kotsios5** [comment]
Reproduced. Thanks!
