### ISSUE TITLE
REST: post on ads not working

### ISSUE THREAD

**Issue by Tyvain** [yclas/yclas#2354]
**POST** method on **ads** service to create an ad is not working

url: 
`https://finvalab.com/api/v1/ads?user_token=XXX`

request params:
```
"id_user" : "15"
"id_category" : "41"
"title" : "testTitle"
"description" : "testDescription"
```

also post with params in url (same problem): 
`https://finvalab.com/api/v1/ads/?user_token=XXX&id_category=41&title=Some title&description=AD description `

**Problems:**
- the ad is not created 
- there is no error message in the response
- response of the request: the list of my ads (same as a get).

**Comment by neo22s** [comment]
Hello,

Just tested at your site, all working good ;)
