### ISSUE TITLE
Theme License splash: License validation error, please insert again.

### ISSUE THREAD

**Issue by rikeshrajbangshi** [yclas/yclas#2357]
Certainly when I logged into my admin panel I saw this message:

I'm using self Hosted Pro.

Info
License validation error, please insert again.
Theme License splash
Please insert here the license for your theme.

LICENSE 

I have used my License Key only in one domain only. www.vintecincopt.com

And I can't create New ticket also from my support panel.

Date: 2016-11-23 10:20:02
Order ID: 3578

**Comment by neo22s** [comment]
Hello,

This is not a support system, please contact us to info@yclas.com

Your support has expired, if you need private support buy at https://selfhosted.yclas.com/support

Regards
