### ISSUE TITLE
Only logged in users can see ad details

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2359]
We can "hack" the model ad, so when we return the description if user is not loged in we show a login button.

Same for custom fields and price address etc...

or even easier not loged in displays another view...asking you to login.

**Comment by oliverds** [comment]
https://github.com/oliverds/openclassifieds2/commit/2a44f413afdd65fcf2675cca340c40cb9cc66c93

New config `login_to_view_ad `. If enabled only logged users can view single ads https://github.com/oliverds/openclassifieds2/commit/2a44f413afdd65fcf2675cca340c40cb9cc66c93#diff-31ad60b3d1dec8aa6f7361170afe03a4R321.
