### ISSUE TITLE
Redirecting guest user after checkout

### ISSUE THREAD

**Issue by kotsios5** [yclas/yclas#2364]
Example:
A guest posts an ad, he is redirected to the thanks page where he choose the option to feature the ad. He adds a coupon and the total becomes '0' and he clicks to proceed. The ad becomes featured but he is redirected to the login page with the error message 'You do not have permissions to access Profile orders', since we redirect orders with amount = 0 to the profile orders page. 
https://github.com/yclas/yclas/blob/master/oc/classes/controller/ad.php#L904  

Should we check if the user is logged in and redirect unregistered users to a different page?

**Comment by neo22s** [comment]
ups! good point! since he never loged in before and since the account was just created.... that happens.

So lets check if loged in redirect him to orders, otherwise to the ad?

**Comment by kotsios5** [comment]
Redirecting them to the ad sounds good.
