### ISSUE TITLE
yclas own server version elasticemail enabled/disable button is not showing.

### ISSUE THREAD

**Issue by MediaExces** [yclas/yclas#2367]
yclas own server version elasticemail enabled/disable button is not showing.

i can't send with elasticemail, i have a account there.
Also send test mail button gives: The requested URL oc-panel/settings/emailtest was not found on this server.

Amanda

**Comment by oliverds** [comment]
Hello,

This is not a support system, please contact us at info@yclas.com.

If you require private support, please check our [support services](https://selfhosted.yclas.com/support) for Self-hosted customers.

Regards

**Comment by MediaExces** [comment]
It's your free version which is not working!
Its a BUG. so i don't want to pay for work to do, it's not a install problem or custom job!

**Comment by neo22s** [comment]
Hello,

You can try at yclas.com, we do have free support in there, this is for developers to solve development issues.

Thanks

**Comment by MediaExces** [comment]
try every option on yclas for free support, can't find it, please give me a link. thanks.
