### ISSUE TITLE
Email subscribers CRUD

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2371]
For table "subscribers"

Add it on menu users on the panel only admin access.

**Comment by kotsios5** [comment]
Error on create and update: _oc-panel/Subscriber/create_ and _oc-panel/Subscriber/update/3_

`Kohana_Exception [ 0 ]: The id_ad property does not exist in the Model_Subscribe class`

**Comment by neo22s** [comment]
damn! good!
