### ISSUE TITLE
[Suggestion] VAT Number check 

### ISSUE THREAD

**Issue by vsatmydynipnet** [yclas/yclas#2417]
Hi,

you combine the country with the VAT number part without the country code. E.g. 

AT + X1234567

to check against vies.

For all people working with VAT numbers the VAT number is:

ATX1234567

You should add a note the one has to enter the VAT number without the country part during setup. I needed to check the code to be able to successful enter our VAT number. :-)

Thank you!

**Comment by neo22s** [comment]
agree! its easy to add a hover text.
