### ISSUE TITLE
URL for logging in as ADMIN

### ISSUE THREAD

**Issue by alxferraz** [yclas/yclas#2419]
Hi I couldn't find any information that could lead me to the URL where I can log in as Admin. Can anybody help me?

**Comment by neo22s** [comment]
Hello André,

Theres not any URL to login as admin, is the same login for any role.

Whats your website URL?

regards

**Comment by alxferraz** [comment]
How do I reset my admin email/password?

**Comment by alxferraz** [comment]
I installed locally

**Comment by neo22s** [comment]
If you want to test the best solution is to use https://yclas.com/

This is github issues is meant for developers, if you have any doubt you can always contact us https://yclas.com/contact.html

regards
