### ISSUE TITLE
SMS Auth

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2425]
Research providers and pricing

https://authy.com/
https://auth0.com/authenticate/php/sms
https://www.twilio.com/use-cases/two-factor-authentication
https://www.twilio.com/two-factor-authentication/features/onecode
https://www.sitepoint.com/implement-two-way-sms-with-php/
https://www.sinch.com/products/sms-api/
https://www.clickatell.com/developers/api-documentation/http-api-send-message/

**Comment by neo22s** [comment]
Flow:

- Required phone number CF for user.
- On login, redirect user to verify phone number, we display the number (they can modify it.)
- We send an SMS, if number is different we store it
- Redirect to a page where user inputs the SMS Code.
- If SMS code is correct login the customer

About provider actually nay provider that can send SMS will work since the code can be stored at our db...

**Comment by neo22s** [comment]
https://www.clxcommunications.com/pricing/ --> 0.055€
https://www.twilio.com/sms/pricing/cy --> 0.08233€
https://www.clickatell.com/pricing-and-coverage/message-pricing/#step-4 --> 0.02773€

All of them without taxes.

**Comment by neo22s** [comment]
https://github.com/jackocnr/intl-tel-input

**Comment by masanchezalfaro** [comment]
@neo22s Client chooses the 3rd option. Clickatell

**Comment by neo22s** [comment]
Oh great it has a 2fa php ready xD https://archive.clickatell.com/developers/scripts/php-library/

**Comment by neo22s** [comment]
Also make phone number from user auto populated on publish new.

**Comment by neo22s** [comment]
ok integration done.

Missing and @oliverds please take care

- [ ] Implement on all themes the changes
- [ ] In edit profile an easier way to put the prefix, this plugin looks cool https://github.com/jackocnr/intl-tel-input need to be stored in DB as +XX
- [ ] In edit profile I did a mess and does not look good the input
- [ ] in publish new: automatically set the phone with the user->phone if its set, if theres a post then use the posted phone number. In all themes
- [ ] implement also at yclas.com

I can share my clickatell account so no need to create a new one ;)

**Comment by neo22s** [comment]
@kotsios5 you will take care of docs

https://docs.yclas.com/2-step-sms-authentication/ --> how works, how to register in clickatell, and get API number 

How works web owner

- Activate 2 step SMS in general settings
- Create clickatell account
- Put API
- Now customers that set a phone number will have 2 step sms.


How works customer:

- customer registers or publish new item
- goes to edit profile and sets a phone number
- ready
