### ISSUE TITLE
Google social login - remove "Manage your contacts" permission

### ISSUE THREAD

**Issue by kotsios5** [yclas/yclas#2428]
https://yclas.com/panel/support/ticket/29713

This is the permissions we ask to users to allow:
http://i.imgur.com/3a5ULNP.png

It seems "manage your contacts" raise concerns to users and they could avoid registering. It's also the same when you try to login to yclas.com using Google social login.

We can remove it by changing this line https://github.com/yclas/yclas/blob/master/oc/vendor/hybridauth/hybridauth/Hybrid/Providers/Google.php#L22 from:
`public $scope = "https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/plus.profile.emails.read https://www.google.com/m8/feeds/";`

to:
`public $scope = "https://www.googleapis.com/auth/plus.login https://www.googleapis.com/auth/plus.profile.emails.read";`

Google social login still works and users won't be asked to allow the app to manage their contacts.

**Comment by neo22s** [comment]
thats great! but when updating hybridauth... we need to be careful. maybe extending the class?

**Comment by kotsios5** [comment]
@neo22s seems not necessary.. It's already remove for the next version:
https://github.com/hybridauth/hybridauth/blob/master/src/Provider/Google.php#L53
