### ISSUE TITLE
Bootstrap migration to v4

### ISSUE THREAD

**Issue by oliverds** [yclas/yclas#2449]
> ... we’ll be doing our best to keep all the classes, features, and docs URLs as they appear now in this release.

https://blog.getbootstrap.com/2017/08/10/bootstrap-4-beta/

First Beta released. A release date seems closer.

**Comment by neo22s** [comment]
lot of work is coming!! ups

**Comment by oliverds** [comment]
**Migrating to v4**

> Bootstrap 4 is a major rewrite of the entire project. The most notable changes are summarized below, followed by more specific changes to relevant components.


http://getbootstrap.com/docs/4.0/migration/

**Comment by neo22s** [comment]
ufff hahahah

**Comment by neo22s** [comment]
https://github.com/jbarreiros/bs4-utilities-for-bs3 maye helps?

**Comment by neo22s** [comment]
maybe helps http://upgrade-bootstrap.bootply.com/

**Comment by oliverds** [comment]
Since BS4 is a major rewrite I think we need a new and shiny Bootstrap 4 base theme that uses the new features. After completed we can start migrating all our other themes too.

Currently working on it...

![bootstrap4](https://user-images.githubusercontent.com/7003648/37068747-d57531c6-2175-11e8-9b07-349d695287cd.png)

**Comment by neo22s** [comment]
looks great!

**Comment by DonPramis** [comment]
This look awesome...

**Comment by oliverds** [comment]
> Since BS4 is a major rewrite I think we need a new and shiny Bootstrap 4 base theme that uses the new features. After completed we can start migrating all our other themes too.
> 
> Currently working on it...

Retaking it... latest bootstrap version is already v4.3 😬

- [ ] Home

**Comment by oliverds** [comment]
I'm making progress on this.

Bootstrap heavily uses CSS flex, and it's a useful feature.

I'm also restructuring the views folder and splitting views with partials, so it's easier to understand what does each view.

<img width="252" alt="Screen Shot 2019-06-04 at 09 10 38" src="https://user-images.githubusercontent.com/7003648/58885919-a6a57600-86a8-11e9-9385-7f9c42e2e201.png">

**Comment by neo22s** [comment]
This looks awesome 👏👏👏👏

**Comment by topraf** [comment]
Hey any updates on the bootstrap implementation?

**Comment by neo22s** [comment]
@topraf we are working on custom development for paid customers at the moment, will be done, but if you want to make a donation it may speed up the development. thanks

**Comment by neo22s** [comment]
https://github.com/openclassifieds/yclas/issues/3705
