### ISSUE TITLE
error after installation

### ISSUE THREAD

**Issue by ib1e** [yclas/yclas#2451]
After successful installation, when directed to got to website or admin login, the following error is returned: 

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /home/www/wafume.net/oc/kohana/system/classes/Kohana/Config.php on line 109

Fatal error: Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) in /home/www/wafume.net/oc/kohana/system/classes/Kohana/Config.php on line 109

**Comment by neo22s** [comment]
Are you 100% sure your hosting is compatible? doesn't seem ;) are you installing 3.2. right?

**Comment by ib1e** [comment]
Yes. Sure. Installed and removed a few times. Installed an ssl cert, was having redirection issues, removed to begin from scratch once more then the errors persisted. I currently removed it again and have abandoned the project temporary can not dedicate the dev time rt. now. Weill pick it back up in a few weeks.

**Comment by neo22s** [comment]
If you have bought a license please open a support ticket. We will try to help you from there.

Theres something wrong on your hosting I can tell ;)

**Comment by vitin22** [comment]
when a finish to install i have this...

Sorry!

Something went wrong with your request. This incident is logged and we are already notified about this problem.

You can go Back or to our Home page.

**Comment by neo22s** [comment]
It's your hosting compatible? please write us to info@yclas.com we will try to help.

**Comment by crolidge** [comment]
I am not sure but I think I have a similar problem.

My website at https://vagas.com.pt/ is completely unavailable
I haven't done anything for severla days. The last time I logged to the Admin dashboard was about 2 weeks ago when I input the Google Maps API key.
Everything was going well, and now suddenly comes the junbotron dialog:

**Sorry!
Something went wrong with your request. This incident is logged and we are already notified about this problem.
You can go Back or to our Home page.**

What should I do?  Were you really notified of this trouble?
I haven't bough a license yet. I was about to do it, but how can I pay for it if even the free website installation crashes? Nearly 400 Euros is too much for something that fail!

Can you please help me out with this problem and present a solution?
Thanks in advance

**Comment by neo22s** [comment]
Hello,

Have you checked in your hosting log errors?

that error it's from your hosting company.

Also please open a support ticket and a technician will help you.

thanks.
