### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by byionline** [yclas/yclas#2452]
The requested URL /oc-panel/auth/login/ was not found on this server.
After installation whenever I visit on login page it shows 404 Not found also category pages like : http://domainname/housing and others are having same 404 Not found error

**Comment by neo22s** [comment]
This is an issue with mod rewrite please be sure you hosting is compatible.

**Comment by byionline** [comment]
Thank you for help 
I solved it by modifying the apache file 000-default.conf
