### ISSUE TITLE
Register with phone

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2461]
1. we ask phone number
2. phone can not be in use in any other user
3. send sms
4. if sms matches we redirect to ask for email address
5. complete register

**Comment by neo22s** [comment]
Route:

/oc-panel/auth/phoneregister

missing:

implement in all themes view/phoneregister.php

And decide how are we going to display it... an option and then appears the form in the register?

**Comment by oliverds** [comment]
> And decide how are we going to display it... an option and then appears the form in the register?

Perhaps if `general.sms_auth` is enabled we should display a `phoneregister-form` view on https://github.com/yclas/yclas/blob/master/themes/default/views/pages/auth/register.php#L8 instead.

**Comment by neo22s** [comment]
or maybe the 2 of them?
