### ISSUE TITLE
Incorrect Update Notification

### ISSUE THREAD

**Issue by vClouds** [yclas/yclas#2480]
I'm fully sure that, I have installed yclas stack using the below download link https://github.com/yclas/yclas/archive/3.3.0.tar.gz

Now, upon login installed version shows v3.2.0 and update tab results in the below notification
You are not using latest version, please update.

Please advise on the actually installed version v3.3.0 with missing modified version number in core witch results in that fake notification? or the downloaded archive is pointing to v3.2.0

![screenshot from 2017-09-04 22-13-57x](https://user-images.githubusercontent.com/24693741/30035848-5c11f530-91bf-11e7-91df-4adee88028bc.png)

**Comment by neo22s** [comment]
The version is correct https://github.com/yclas/yclas/blob/3.3.0/oc/classes/core.php#L19

Try downloading again, I have downloaded too, and version says 3.3.0

**Comment by neo22s** [comment]
also whats your domain name? and why do you hide it?

**Comment by neo22s** [comment]
![image](https://user-images.githubusercontent.com/241725/30036083-58573f4a-91b0-11e7-86e5-1337330aa9aa.png)

**Comment by vClouds** [comment]
@neo22s Thanks for the feedback
I continued with the update notification anyway and it is now 3.3.0

I have been bothered by others one time upon posting with sensitive details including domain.
On other note, I'm planning for using yclas for special closed network within only our customers; that's only because of nature of business while yclas as I figured it out has too many features of course.
below is the link
https://deal.innoconsultancy.com

**Comment by neo22s** [comment]
@vClouds glad it works! hope you are succesful, thanks.
