### ISSUE TITLE
Forums Settings Returns Error in Admin Panel

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2488]
array_walk() expects parameter 1 to be array, null given
It's been loged in Panel->Extra->Tools->Logs for more information regarding this error.
---------

 parent forum was deleted, but not changed the sibling

**Comment by kotsios5** [comment]
I can't reproduce this issue. When I delete a parent forum, the sibling's parent forum changes to None as expected. Also no errors in the log.

**Comment by neo22s** [comment]
ufff strange... I had this issue before with other customers
