### ISSUE TITLE
Openssl Script Validation Error for Hashkey less than 16.

### ISSUE THREAD

**Issue by alancheongkl** [yclas/yclas#2495]
When try to upgrade from 3.2.0 to 3.3.0, keep getting error as following and not able to solve.
Found out the previous Installation Hashkey doesn't match the length 16. "12345678901" which is 11 only.

> Kohana_Exception [ 0 ]: No valid encryption key is defined in the encryption configuration: length should be 16 for AES-128-CBC ~ APPPATH/kohana/modules/encrypt/classes/Kohana/Encrypt/Engine/Openssl.php [ 56 ]

**Temporary Solved by :** 
1 ) Bypass the openssl checking for hashkey length less than 16 as following : ( **change from 16 to 11** to match existing hashkey "12345678901" as following modification 

File Location : oc/kohana/modules/encrypt/classes/Kohana/Encrypt/Engine/Openssl.php

**From this :**  
`// Validate configuration
                if ($this->_cipher === 'AES-128-CBC')
                {
                        if ($length !== 16)
                        {
                                // No valid encryption key is provided!
                                throw new Kohana_Exception('No valid encryption key $
                        }
                }`

**To This :** 
 `
// Validate configuration
                if ($this->_cipher === 'AES-128-CBC')
                {
                        if ($length !== 11)
                        {
                                // No valid encryption key is provided!
                                throw new Kohana_Exception('No valid encryption key $
                        }
                }
`

This solved the problem temporary and able to update to 3.3.0.

After update done, modify the HASHKEY from '12345678901' to '1234567890123456' and revert the code to Length must be = 16.

This solve my problem, but required all the users need to reset the password, and luckily this is a new site which don't have many users yet.

1) Wondering this will have cause any future trouble or issues.

2) Any other better solutions to solve this instead of using above method ?

3) Believe there's a bugs when having the New Encryption module, which doesn't support if the "HASHKEY" is not equilvalent to 16. Related issues : [https://github.com/yclas/yclas/issues/2176](url)

**Comment by neo22s** [comment]
seems related to https://selfhosted.yclas.com/oc-panel/support/ticket/29936

**Comment by neo22s** [comment]
Hello,

The users are not encoded using the hash key at all.... so no need to reset al passwords.

I see where the problem stands having a 11 key hash ley and now requiring a 16 key.

Thanks for reporting it so we can help other people with similar issues.

The fastest way to fix it is by deleting  oc/config/encrypt.php
