### ISSUE TITLE
Whatsapp API

### ISSUE THREAD

**Issue by alancheongkl** [yclas/yclas#2497]
Hi,
Realize that current whatsapp link can only function on Android.
Which the following is the example of the LINK that it will be re-directed to 

`intent://send/60195675678#Intent;scheme=smsto;package=com.whatsapp;action=android.intent.action.SENDTO;end`

Can I suggest that we just use the default whatsapp API as following : 

`https://api.whatsapp.com/send?phone=15551234567`

Because this will be able to work on any platform and OS.

**Comment by neo22s** [comment]
thanks will be done.
