### ISSUE TITLE
Share options not displayed

### ISSUE THREAD

**Issue by GokulRamasamy** [yclas/yclas#2506]
![adminpart](https://user-images.githubusercontent.com/7909385/30732051-4eb20baa-9f8e-11e7-97e2-af67da5d7686.PNG)
Share(facebook,twitter) options are not displayed in sidebar. Before these options are displayed fine. But now its not displaying properly. I could not update the open classifieds because i changed lot of design in my website.
![share social](https://user-images.githubusercontent.com/7909385/30732045-477cf9a8-9f8e-11e7-9f2c-acca68c30c10.PNG)

So please help me to solve this issue.

**Comment by neo22s** [comment]
whats your domain name? what version of yclas are your using?

**Comment by GokulRamasamy** [comment]
Actually i developing my site in localhost. I am using Open classifieds
2.9.0

**Comment by neo22s** [comment]
in local and you are using 2.9.0? update immediately to 3.3.0. we can not help you please use our support plans https://selfhosted.yclas.com/support

**Comment by GokulRamasamy** [comment]
If i update the open classifieds then i lost my design and my new
functionalities?  How could i update without affect my design and new
functionalities?

**Comment by neo22s** [comment]
please use our support plans https://selfhosted.yclas.com/support
