### ISSUE TITLE
Featured Ad slider on Version 3.3.0

### ISSUE THREAD

**Issue by Lasherza** [yclas/yclas#2512]
Hi,

Apologies if this is not the right forum. I have installed Yclas self hosted veriosn 3.3.0 via my hosting provider. Im from south Africa and cannot really afford the Pro version at this stage.

I have one question please.?

Is the Featured Ad slider enabled in this free lite version of Yclas 3.3.0 ? I have created my site. And marked many test adverts as Featured, but the slider arrows do not appear.

Again if this is the wrong forum i apologise. I am just stumped at the moment and would love this feature to work..

Thanks
Laurence

**Comment by neo22s** [comment]
Hello, 

Please you need to use the paid support or contact us via the contact form.

This is not a forum ;) is the issues reporting place

thanks
