### ISSUE TITLE
Yclas thumnail images cropped

### ISSUE THREAD

**Issue by elppr** [yclas/yclas#2516]
Yclas version 3.3.0  thumbnail images show cropped. I changed the media setting but have not been successful. Please advise. Thank you

**Comment by neo22s** [comment]
Hello,

Whats your site URL? and what do you mean crop? can you show an example? which theme are you suing?

**Comment by elppr** [comment]
By cropped I mean the image does not display in its entirety, part of the image shows. Please see the problem here http://greekads.com/international-real-estate-listings/agent-directory

Thanks

**Comment by neo22s** [comment]
you need to put the size of thumb to the default, and reupload the images ads.

**Comment by elppr** [comment]
The default is 200x200? I did what  you said, re uploaded the image but the problem persists. Thanks

**Comment by neo22s** [comment]
150px

**Comment by elppr** [comment]
Image height blank
mage width 4000
thumbnail 150x150
Please see, it is the second, smaller image. This is worse. Thank you

**Comment by neo22s** [comment]
sorry thumb is 200x200  width is 1200px, why 4000? thats really really big! its for web.

**Comment by elppr** [comment]
Please take a look at this.
http://greekads.com/international-real-estate-listings/agent-directory
Anchor Associates NYC
50px × 150px

"why 4000? thats really really big!". What would you suggest? Thanks

**Comment by neo22s** [comment]
1200px

**Comment by elppr** [comment]
Thanks. I will change that. Please look at the new image I uploaded, a small image,(the anchor company) it looks ok. The problem is that the script does not resize the image. Thank you.
http://greekads.com/international-real-estate-listings/oc-panel/myads/update/14

**Comment by neo22s** [comment]
all is working good from our end please if you need private support open a ticket at our support center:

https://selfhosted.yclas.com/oc-panel/support/new

thanks
