### ISSUE TITLE
Filter ads by language

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2517]
Filter ads by language - ads will have a custom field language, auto filled when posting. And when
a language selected you will see only ads on that language.

Update docs.yclas.com

**Comment by neo22s** [comment]
@oliverds podemos hablar de este hoy? a ver como lo implementamos ;)

**Comment by oliverds** [comment]
Por supuesto :)

> @oliverds podemos hablar de este hoy? a ver como lo implementamos ;)
