### ISSUE TITLE
Admin -> Advertisement - Loading loop

### ISSUE THREAD

**Issue by trueliarx** [yclas/yclas#2533]
I've just done a fresh installation with scripts from github (master).
When I go in the administrator panel and hover on the "Classifieds->Advertisements" the mouse shows a loop circle and when I click it doesn't open the relative page to manage the advertisements.
If I go directly to oc-panel/ad/index the page works regularly.

The same happens after another fresh installation.

Tested on:
Windows - apache2 + php 5.6 + mysql 5.5.42
Linux centos - apache2 + php 5.6 + mysql 5.5.42

Browsers: opera 48, firefox 56 64bit

**Comment by neo22s** [comment]
Hello,

Whats's your URL?

What error do you have on the error log?

**Comment by trueliarx** [comment]
Hi,
I'm testing on local servers.

The request that is blocked is http://localhost/yclas/oc-panel/ad/index?rel=ajax
while on other Menu Items I don't have such problem.

--client side errors/notices--
default+en.I.js:574 This page is calling an old version of the Custom Search API, which is deprecated and will stop working soon. In order to avoid an outage for the search results, the call for search results must be updated to the current version of the Custom Search API https://developers.google.com/custom-search/docs/element.
[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/

--logs--
2017-10-25 02:25:50 --- ERROR: ErrorException [ 8 ]: Undefined index: subscriptions_expire ~ APPPATH\classes\controller\panel\settings.php [ 249 ] in \www\yclas\oc\kohana\system\classes\Kohana\Kohana\Exception.php:110

**Comment by neo22s** [comment]
Please use latest which is 3.3.0 and use php 7

Also disable addblock

regards
