### ISSUE TITLE
CarQuery

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2559]
Or similar

http://www.carqueryapi.com/documentation/getting-started/

If custom fields, year, make, model exists and the carquery is enabled (new option in general?) then we load the selects ;)

**Comment by oliverds** [comment]
How it works...

- CarQuery needs to be enabled in general settings
- "Select" custom fields for year, make and model with name `year`, `make` and `model`

**Comment by neo22s** [comment]
@oliverds looks great!!

@kotsios5 test and docs please!! :D
