### ISSUE TITLE
Import ads with custom fields

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2560]
improve the tool to allow fields with prefix cf_

**Comment by oliverds** [comment]
First, we check if csv have has custom fields. If not, csv with _normal_ fields.

https://github.com/oliverds/openclassifieds2/commit/fe183b49f46a55e1df994ba86b38ac3100e505bb#diff-f17ed7b5bf9e32a294bc2eb16a7c0defR74

**Comment by neo22s** [comment]
awesome!! @kotsios5 can you please update the docs? and update the import ads file to put a new one with CF as example?

**Comment by kotsios5** [comment]
It doesn't work for websites that already imported ads. On local, I have imported ads previously so the table _adsimport existed, it only worked when I deleted the table. Same happens on .tk.

**Comment by oliverds** [comment]
Ok. It seems we should drop the `adsimport` table first.

**Comment by rtuz2th** [comment]
Has this ever been fixed? Just started messing around with a demo shop, the only file I get to work is the sample file, at least it will upload without a problem, processing does not work. Uploading a sample file with my custom fields added is not possible.

**Comment by neo22s** [comment]
Yes this is working perfectly. Please open a support ticket github it's for developers

**Comment by rtuz2th** [comment]
I tried that before, they just told me it would work but it obviously does not, so I just thought anyone here might knows a workaround

**Comment by neo22s** [comment]
Hello, it does work, you need to be sure the file is correctly done. Many customers are using this. Please open a support ticket. thanks

**Comment by rtuz2th** [comment]
Okay. Thank you!
