### ISSUE TITLE
Zenith Payment Gateway

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2566]
https://trello.com/c/4ci83a0U/493-zenith-payment-gateway

**Comment by neo22s** [comment]
ok, only missing adding the PRO URLs ;)

**Comment by oliverds** [comment]
Nop https://github.com/oliverds/openclassifieds2/commit/f3d5fc714f0b48a47de208473c0efcee25310547#diff-21e92490fc82e7f71961192a35946044R15. Found pro url in a woocommerce plugin hehe

**Comment by neo22s** [comment]
hahahahahah xD
