### ISSUE TITLE
banned_domains.json

### ISSUE THREAD

**Issue by datio** [yclas/yclas#2579]
Hi @neo22s

I'd like to request permission to add the banned domains list into [MailChecker](https://github.com/FGRibreau/mailchecker/issues/117)
I think you'd be more than welcome to add it yourself there BTW.

**Comment by neo22s** [comment]
Hello,

Thanks for asking, but this DB belongs to https://github.com/ivolo/disposable-email-domains/ ;) so you need to ask them.

Also we have a open source PHP library.https://github.com/neo22s/emailvalidator
