### ISSUE TITLE
Zenith Payment Gateway requires user's phone

### ISSUE THREAD

**Issue by oliverds** [yclas/yclas#2585]
User phone is mandatory to process payments.

If users have not set a phone on their profile redirect them before checkout? https://github.com/yclas/yclas/blob/c258973a4051ca363697c9c81c9df5d8f9afc576/themes/default/views/pages/zenith/button.php#L6

**Comment by neo22s** [comment]
ufff yes ... what else can we do... most stupid thing ever. only if zenith payment is on.
