### ISSUE TITLE
Compatible with PHP 7.2?

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2589]
Check if works out of the box.

**Comment by neo22s** [comment]
sent by @kotsios5 

The error I was getting regarding mcrypt was:
Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128'

Here's the changes to fix this error:
https://github.com/kotsios5/yclas-test/compare/3c405e240997...1f837938e567

Since two of the files are under the Kohana directory, how should we proceed?

**Comment by neo22s** [comment]
Hello!!

I think I need to discuss it with the koseven group!

Using this:

'cipher' => 'MCRYPT_RIJNDAEL_128',

Will make to use a string instead of a DEFINE, right? what if it's empty better like

'cipher' => '',

A​nd if we make this changes does still work in older versions?

**Comment by kotsios5** [comment]
@neo22s yes it works in the older versions too

**Comment by neo22s** [comment]
all seems to work good! let's do the same for yclas.com ;)
