### ISSUE TITLE
Advance search not case insensitive

### ISSUE THREAD

**Issue by kotsios5** [yclas/yclas#2597]
Currently searching for ads is case sensitive. For example, if I the input  "test" it won't return in the results the ad called "Test".

**Comment by neo22s** [comment]
we have different ways of solving this.

Putting all to lower, on PHP or in MySQL using LOWER()

Another way is changing ... again the Collate to COLLATE UTF8_GENERAL_CI

CI stands for case insensitive. utf8mb4_unicode_ci we could try...

I think easiest is to put it in lower ..... and then it's working.

**Comment by neo22s** [comment]
Ok works like this:

ALTER TABLE oc2_ads CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

**Comment by neo22s** [comment]
the issue only happens on old sites that we migrated before...  we had wrong collate.
