### ISSUE TITLE
Improve orders/checkout page

### ISSUE THREAD

**Issue by kotsios5** [yclas/yclas#2617]
Add more information to views/pages/ad/checkout.php and views/oc-panel/profile/orders.php

Similar to https://cdn.yclas.com/images/cms/1485253864.11.PNG

**Comment by neo22s** [comment]
what kind of info?

**Comment by kotsios5** [comment]
User name, email, location, address on the right top corner and move the VAT details and order ID on the left corner.

**Comment by neo22s** [comment]
greattt
