### ISSUE TITLE
Redirect to referrer after login

### ISSUE THREAD

**Issue by kotsios5** [yclas/yclas#2618]
https://selfhosted.yclas.com/oc-panel/support/ticket/30353
and
https://selfhosted.yclas.com/oc-panel/support/ticket/30315
https://youtu.be/f7uU1rIIOLg

I can reproduce this issue on both sites. Example:
1. Open the site from google search results
2. Login
3. If login credentials are correct it redirects to google homepage

**Comment by neo22s** [comment]
fuck thats becasue get the referral and redirects...

WE should check before the redirect if the URL it's from the same domain name....
