### ISSUE TITLE
Homepage map

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2622]
We should enable in all themes an easy way to include the map in the homepage

Something as simple as this:

<iframe width="100%"  height="400px" border=0 src="/map.html"></iframe>

Any ideas for more settings? like they can choose where maybe?

**Comment by kotsios5** [comment]
Yes, choosing where to show the map in the homepage will be useful. Other options could be the _height_ of the map and  _allowfullscreen_.

**Comment by neo22s** [comment]
that sounds like a great idea!!!
in all the themes?
or maybe as general configs?

**Comment by kotsios5** [comment]
In general configs would be easier for us but if we have an option to choose where to show the map in the homepage, it seems better to have it in each theme options because some themes have different content.

**Comment by neo22s** [comment]
yeah...let do a new set of settings for each theme in the home tab?

Map - none, top, bottom
Map height
Map allowfullscreen

How do you see it?

**Comment by kotsios5** [comment]
> Map - none, top, bottom

At the time we will have the same options for all the themes we can have it in general configs (Settings -> Advertisement -> Google Maps)

**Comment by neo22s** [comment]
ok! sounds great! yes better ;)
