### ISSUE TITLE
Facebook login update

### ISSUE THREAD

**Issue by kotsios5** [yclas/yclas#2625]
> In March, we're making a security update to your app settings that will invalidate calls from URIs not listed in the Valid OAuth redirect URIs field below.This update comes in response to malicious activity we saw on our platform, and we want to protect your app or website by requiring a new strict mode for redirect URIs.

https://developers.facebook.com/docs/facebook-login/security/#strict_mode

**Comment by neo22s** [comment]
what do we need to do?

**Comment by kotsios5** [comment]
No idea at the moment, maybe nothing but I created the issue so I can check it soon.

**Comment by neo22s** [comment]
hehehe ok!
