### ISSUE TITLE
Redirect after register or login - installation on folder

### ISSUE THREAD

**Issue by kotsios5** [yclas/yclas#2633]
`base_url: localhost/yclas340/`

After register or login it redirects to localhost/yclas340/yclas340/

**Comment by neo22s** [comment]
os subdomain or folder?

**Comment by kotsios5** [comment]
Yeah folder.. thanks

**Comment by neo22s** [comment]
damn... so strange :(

maybe due to this https://github.com/yclas/yclas/issues/2618 ?

**Comment by kotsios5** [comment]
The redirection after login seems fixed with 
https://github.com/kotsios5/openclassifieds2/commit/27851b059d2c9f34163286425446f44e5a1f6dbb

**Comment by neo22s** [comment]
and the redirect from google works?

**Comment by kotsios5** [comment]
I tested with Instagram, it works
