### ISSUE TITLE
Use of undefined constant MCRYPT_RIJNDAEL_128 error - possibly mcrypt related

### ISSUE THREAD

**Issue by mohdmunsif** [yclas/yclas#2651]
Installed Yclas  3.4 on WAMP PHP 7.2.2 - with no mcrypt. Installation page did show the potential error with mcrypt - but it installed and created the DB nonetheless. 

Still once the domain is loaded, the only thing being shown is the following error: 

ErrorException [ 2 ]: Use of undefined constant MCRYPT_RIJNDAEL_128 - assumed 'MCRYPT_RIJNDAEL_128' (this will throw an Error in a future version of PHP) ~ APPPATH\kohana\modules\encrypt\config\encrypt.php [ 14 ]

**Comment by neo22s** [comment]
if you want to test yclas, best is to do it at ylclas.com

**Comment by kotsios5** [comment]
Hello @mohdmunsif 

Please comment out the following lines in order to fix that error:
1. https://github.com/yclas/yclas/blob/master/oc/kohana/modules/encrypt/config/encrypt.php#L14-L15
2. https://github.com/yclas/yclas/blob/master/oc/config/encrypt.php#L8

**Comment by mohdmunsif** [comment]
@kotsios5 Thank you for the update. That seemed to have fixed it.

@neo22s thanks for the fast turnover! Sorry that I am trying on my own box, easier for me to do stuff here :)
