### ISSUE TITLE
Muhammad Usman

### ISSUE THREAD

**Issue by Emyoosol** [yclas/yclas#2652]
![2018-03-18_13-41-16](https://user-images.githubusercontent.com/37496067/37564165-21562be6-2ab2-11e8-8807-bfa54cb4c7b3.jpg)

want a solution to a problem and the problem is after ads gets expired say if i set my website(yclas) ads expire in 6 days then i want these ads permanently and automatically be deleted along with the uploaded images in the hosted server directory (where website files present on server). problem is even the ads expired at expiration date the ads stays there in the expired tab along with ads images which results occupying server space which makes impossible to manage a website  hosted with yclas. please give a solution with a cron job or integrate that functionality.

**Comment by neo22s** [comment]
We only accept issues that are bug reports or feature requests. Bugs must be isolated and reproducible problems that we can fix within the Yclas core. Please read the following guidelines before opening any issue.

Search for existing issues. We get a lot of duplicate issues, and you'd help us out a lot by first checking if someone else has reported the same issue. Moreover, the issue may have already been resolved with a fix available.
Create an isolated and reproducible test case. Be sure the problem exists in Yclas code.
Include a live example. Make use of screenshots if needed.
Share as much information as possible. Include operating system and version, browser and version, version of OC, customized or vanilla build, etc. where appropriate. Also include steps to reproduce the bug.
