### ISSUE TITLE
want to set cron for deleting expired ads along with images

### ISSUE THREAD

**Issue by Emyoosol** [yclas/yclas#2653]
i am using shared hosting and want expired ads be deleted along with images so that hosting space do not compromise. plz help me set that cron job

**Comment by neo22s** [comment]
We only accept issues that are bug reports or feature requests. Bugs must be isolated and reproducible problems that we can fix within the Yclas core. Please read the following guidelines before opening any issue.

Search for existing issues. We get a lot of duplicate issues, and you'd help us out a lot by first checking if someone else has reported the same issue. Moreover, the issue may have already been resolved with a fix available.
Create an isolated and reproducible test case. Be sure the problem exists in Yclas code.
Include a live example. Make use of screenshots if needed.
Share as much information as possible. Include operating system and version, browser and version, version of OC, customized or vanilla build, etc. where appropriate. Also include steps to reproduce the bug.
