### ISSUE TITLE
Small bug in changepass when using yclas at https: //

### ISSUE THREAD

**Issue by Matze-Germany** [yclas/yclas#2668]
Hello developers,

Martina from infoatyclas.com does not answer if she has forwarded my bug description to the developers. So here again:

Small bug in changepass when using yclas at https: //
 
Please make the following steps:

1. Click Login
2. Click forgot password
3. Enter the e-mail address ==> Send
4. Link in user-email is ok ==> protocol: https: // .. / oc-panel / auth / ql / ...
5. Click this email link
6. Browser address bar changes from https:// to http:// ==> No encryption :-(
 
https: // .. / oc-panel / profile / changepass ==> ok
http: // .. / oc-panel / profile / changepass ==> not ok

Yclas Self-Hosted Version: 3.4.0
PHP Version: 7.1.2
Browser Version: Mozilla Firefox 59.0.2
OS Version: Windows 10 (Version 1709, Build 16299.309)
 
Maybe the developers will eventually find the mistake.
Or not. :-)
 
 
Best Regards,
Matze from Germany

**Comment by oliverds** [comment]
Hi @Matze-Germany,

Thanks for reporting. https://github.com/oliverds/openclassifieds2/commit/fcd1bb73b27ba74f36a4009d0ed7788c375bb21a fixes it.

Regards,
Oliver

**Comment by neo22s** [comment]
hello @Matze-Germany what's your domain name URL?

**Comment by Matze-Germany** [comment]
Hello Chema,

my url is https://kleinanzeigen-webwerbung.de.


Regards,
Matze



Von: Chema 
Datum: Freitag, 6. April 2018 08:27
An: yclas/yclas 
Cc: Matze-Germany ; Mention 
Betreff: Re: [yclas/yclas] Small bug in changepass when using yclas at https: // (#2668)

hello @Matze-Germany what's your domain name URL?

**Comment by Matze-Germany** [comment]
Hello Chema,

Surely I've already thought about it.
About the Pro Version.
Unfortunately, at the moment it can only cover the server costs. Maybe later...

Sorry for my english, use google translator. 


Regards,
Matze


Von: Chema 
Datum: Freitag, 6. April 2018 11:16
An: yclas/yclas 
Cc: Matze-Germany ; Mention 
Betreff: Re: [yclas/yclas] Small bug in changepass when using yclas at https: // (#2668)

Thanks @Matze-Germany

Have you considered our PRO package? :)
