### ISSUE TITLE
Yclas User Issue 

### ISSUE THREAD

**Issue by AdsKhan** [yclas/yclas#2700]
Hello , I have issue on when user try to publish new Ad Showing this Error

> **Your profile has been disable for posting, due to recent spam content! If you think this is a mistake please contact us.**

Pleas help me any one, Idnt know where to Ask help on Yclas Sofware issues. Thanks

**Comment by neo22s** [comment]
Hello,

This is not the support center ;)

https://yclas.com/contact.html
https://docs.yclas.com/how-to-avoid-spam-in-my-site/

**Comment by neo22s** [comment]
https://yclas.com/contact.html
https://docs.yclas.com/how-to-avoid-spam-in-my-site/
