### ISSUE TITLE
Compatibility checker is not verifying that .htaccess and mod_rewrite function properly

### ISSUE THREAD

**Issue by honkingantelope** [yclas/yclas#2708]
Admittedly I'm new to web server administration.  It took me a few failed install attempts (a skeleton site comes up, but everything is 404) to trace the issue down to apache2.conf not allowing the rewrite rules to be picked up from .htaccess

It doesn't seem it would be all that difficult for the pre-install checker to verify that mod_rewrite is actually functioning properly.  Ditto for php-xml package as well.

**Comment by neo22s** [comment]
Sure please make a PR and we will review it.
