### ISSUE TITLE
Translations of "names"

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2716]
How to add translations of categories, locations,  etc...

Keep seoname

Maybe a table translations?

id_translation
table : categories, locations
id_item . reference of the table
locale
name
description

Or using the config table? as we do in Yclas? we store an array....could be something like i18n.categories_es_ES

then when editing a category/location able to add new translations and delete them?

**Comment by oliverds** [comment]
- Added a new `translation_name` column to store json translations.

- Name translations can be updated on edit category/location. (Multilingual mode must be enabled)

- New method `->translate_name()` to get translation of name.

**Comment by oliverds** [comment]
PR updated :)

- Renamed `translation_name` to `translations` 

- Name and Description translations can be updated on edit category/location.

- New method ->translate_description() to get translation of description.

**Comment by neo22s** [comment]
![image](https://user-images.githubusercontent.com/241725/42328664-2cb9555e-806f-11e8-8f98-7da8ec1c53d2.png)

**Comment by neo22s** [comment]
@oliverds works great!! only this improvements, then test better and I will release :D

**Comment by neo22s** [comment]
ups and also update the docs please :D

**Comment by oliverds** [comment]
I think your i18n.locale config is en_UK that's why en_US is still selectable.

Yep, still doing more testing.

**Comment by neo22s** [comment]
es_ES 

![image](https://user-images.githubusercontent.com/241725/42333595-71402c5a-807b-11e8-9f7a-966af3888908.png)
