### ISSUE TITLE
Ad custom fields do not appear when posting a listing 

### ISSUE THREAD

**Issue by Cestis** [yclas/yclas#2732]
Just installed a fresh site from master (3.5.0?) and custom fields for advertisements are not appearing. They are returned correctly from an API though, just JS is not adding them to the form (and you can still post an ad even though these custom fields are required).

**Comment by neo22s** [comment]
Hello Cestis,

This is not a support portal, this is github for developers. Please open a support ticket if you have Professional support or contact us to info@yclas.com

thanks.
