### ISSUE TITLE
Entering invalid license breaks site

### ISSUE THREAD

**Issue by JReming85** [yclas/yclas#2734]
navigating to /oc-panel/theme/license

and entering any combination and submitting will break install / reinstall

**Comment by neo22s** [comment]
That is really strange, please write to us to info@yclas.com with all the info.

**Comment by JReming85** [comment]
Figured out the issue, still not sure how it all came together.

I have the "RewriteRule .* index.php/$0 [PT]" uncommented in my apache conf and all worked just fine, until I went to go test the license validation at which point it started 404ing all static files.

Pages would load but no css and a few other files would not load.

Its strange because it worked fine prior to testing the validation, but broke after.

It wasn't till a little later that I figured it out, sorry should have posted a reply.

**Comment by neo22s** [comment]
whats your domain url?
