### ISSUE TITLE
Dropzone will not work if bbcode is disabled in Publish New

### ISSUE THREAD

**Issue by Matze-Germany** [yclas/yclas#2743]
Hello developer,

since the update to version 3.5 I searched for the error.
Unfortunately, Dropzone only works with bbcode enabled in Publish New.

If bbcode is disabled, you will not be able to click or submit Publish New.
In the debugger of Firefox probably an error in themes/default/ js/new.js is displayed.
Line 380: $ ('textarea [name = description]: not (.disable-bbcode)'). Sceditor ('instance'). UpdateOriginal ();

Please check the error. :-)

Greetings Matze

**Comment by neo22s** [comment]
thanks a lot! we will take a look ;)

**Comment by DonPramis** [comment]
same here...

**Comment by neo22s** [comment]
https://github.com/yclas/yclas/issues/2748

**Comment by Matze-Germany** [comment]
Thank you, works great. :-)

The user can put 1 image more in the dropzone field of the browser before the warning appears: "You can not upload any more files."

So with 4 allowed pictures, the warning only appears at picture number 6 and not at picture number 5. But only 4 pictures will be uploaded correctly.

But no matter. This warning will only be seen by users who want to upload more images than allowed. ;-)
