### ISSUE TITLE
Request Fontawesome Instead of Icon img on Category

### ISSUE THREAD

**Issue by DonPramis** [yclas/yclas#2749]
oc/classes/model/category.php

Only suggestion why not using fontawesome as icon  on OC Panel > categories > update > upload category icon.

Here is the sample of what i mean I do on category:
https://i.imgsafe.org/34/343a6806aa.png

I noticed that icon image faded/not very clear the color, specially on tablet and mobile. Fontawsome makes it no issues. 

I checked themes using icons have this issues.

Thanks.

**Comment by neo22s** [comment]
https://github.com/yclas/yclas/pull/2898
