### ISSUE TITLE
Error tras renovar destacado

### ISSUE THREAD

**Issue by matiasoporto** [yclas/yclas#2766]
Cuando el visitante lo paga efectivamente se destaca. Pero cuando el aviso destacado vence y el usuario lo vuelve a destacar no aparece en el listado como destacado arriba del todo. Aunque sí en los Widgets de destacados.

**Comment by neo22s** [comment]
Hola,

Esto es github es para los desarrolladores no para obtener soporte de uso de la plataforma.

saludos
