### ISSUE TITLE
Black list not working properly

### ISSUE THREAD

**Issue by net44** [yclas/yclas#2769]
I have blacklisted some words but sometimes users still can add new ad with this word, For example if you ban word "yclas" then when somebody write the same word in capital letter "YCLAS" or "YCLAS." or "YCLAS.COM" it will not be banned. 
Can you add an option, when an advertisement containing part of prohibited word will not be added.

**Comment by neo22s** [comment]
you mean is case sensitive?

**Comment by net44** [comment]
yes, and sometimes if you ban "WORD" and somebody add WORD.COM or WORD123 or www.word.tld, it will not be banned
