### ISSUE TITLE
Guide to add new language

### ISSUE THREAD

**Issue by mjhpour** [yclas/yclas#2783]
Hi. My question is how to create a new translation for the site. in the admin panel, there is no button to create a new translation. we have a folder with the name "languages" in the project. how to add a new translation to this folder and what is the structure of content in the ".po" and ".mo" files. did we have any structure to create a new language and generate ".mo" file?

**Comment by neo22s** [comment]
Hello,

Are you a developer? if you are this is something truly simple.

If you are not please contact us at info@yclas.com to get support.

**Comment by mjhpour** [comment]
Yes, I am. but previously I do not work with the ".po" ".mo" files!

**Comment by neo22s** [comment]
https://docs.yclas.com/how-to-change-texts/
https://github.com/yclas/yclas/tree/master/languages

**Comment by mjhpour** [comment]
Hi, I make a copy of "ar" language and change it to "fa_IR" for Persian language.

![vs-code](https://user-images.githubusercontent.com/11529751/47524225-e13f6880-d8a6-11e8-9f9f-02c40bf4528c.png)

In the panel, I selected it and try to edit language. after creating a translation for word "panel" and set "fa_IR" to active the translation was not changed.

![panel](https://user-images.githubusercontent.com/11529751/47524349-3da28800-d8a7-11e8-8846-55846dd648f5.png)

**Comment by mjhpour** [comment]
The languages that were added to the PANEL > SETTINGS > GENERAL > REGIONAL is CASE SENSITIVE and SHOULD match with the name of the folder under the "languages" folder. after correction, it was work for me.

**Comment by mjhpour** [comment]
The method that was generate and render the available languages was under the:

`..\oc\classes\i18n.php --> get_selectable_languages()`

```php
class I18n extends Kohana_I18n {}
```
