### ISSUE TITLE
Framework migration

### ISSUE THREAD

**Issue by mjhpour** [yclas/yclas#2784]
Hi.

Did you have any plan to migrate to the new fresh frameworks like [Symfony](http://www.symfony.com/) of [Laravel](https://laravel.com/)? This new tools was developer friendly and have good tools and ecosystem.

**Comment by neo22s** [comment]
No plans at all we use koseven which is updated and maintained. If you are a developer you will find it super straight forward to be used.

regards

**Comment by mjhpour** [comment]
Yes, it was. Thanks.
