### ISSUE TITLE
Google not accepting old signin button style (g+)

### ISSUE THREAD

**Issue by ramanrvg** [yclas/yclas#2796]
Hi,
I am using self hosted pro without support. while submitting verification to Google OAuth Consent, they say that Signin button should be as per Google new guidelines.
Do we have any update?

Regards,
Venkat

**Comment by neo22s** [comment]
Hello Venkat,

This is for developers. Are you a developer?

You need to indicate a fix. Include screenshots software version etc.

**Comment by ramanrvg** [comment]
No. I am user of yclas.  How do I report issues..

**Comment by ramanrvg** [comment]
Version used is 3.5.0

![loginscreen 2018-11-23](https://user-images.githubusercontent.com/25920305/48941483-b3028680-ef41-11e8-9499-2166dcb2c970.png)
![googleresponse 2018-11-23](https://user-images.githubusercontent.com/25920305/48941484-b3028680-ef41-11e8-97e6-597079c80802.png)

I guess the given attachments are good enough to understand the issue.  Let me know if you need anything specific 
Thanks

**Comment by neo22s** [comment]
Can you please share the link on google sign-in branding guidelines?

**Comment by ramanrvg** [comment]
https://developers.google.com/identity/branding-guidelines#top_of_page

**Comment by ramanrvg** [comment]
Thanks for updating.  Appreciate the quick resolution.

**Comment by ramanrvg** [comment]
After successfully authorising Google signin, I am seeing 403 Forbidden while redirecting
![2018-11-26](https://user-images.githubusercontent.com/25920305/49033679-cfb6ec80-f1d5-11e8-90d9-1f5bdefd48d4.png)

**Comment by neo22s** [comment]
That's a server error check it on your servers log

**Comment by ramanrvg** [comment]
The server did not say any forbidden error for /social/login/1 url, but only for the above URL with parameters.  Is it still server error?

**Comment by ramanrvg** [comment]
Ok thanks for replying. Got it fixed by the server team.
