### ISSUE TITLE
add Java script html

### ISSUE THREAD

**Issue by icexcris** [yclas/yclas#2803]
when I try to add

![capture](https://user-images.githubusercontent.com/10870128/49888345-7a224700-fe47-11e8-9685-b13b52b41973.PNG)

this error appears: 
![capture1](https://user-images.githubusercontent.com/10870128/49888344-7a224700-fe47-11e8-8bfd-97b467cf1908.PNG)

**Comment by neo22s** [comment]
Hello,

As indicated github issues are for developers. If you need support please contact info@yclas.com.

Regards
