### ISSUE TITLE
Can't update array with "+=",  Selects not added back to query builder after count for pagination.

### ISSUE THREAD

**Issue by mrx** [yclas/yclas#2809]
https://github.com/yclas/yclas/blob/39cdab18e439d41a7e003ecd324ae856a7a0957f/oc/classes/orm.php#L115

'+=' won't work if array key already exist in $this->_db_pending
// Add back in selected columns
$this->_db_pending += $selects;

change to:
$this->_db_pending = array_merge($this->_db_pending, $selects);

**Comment by neo22s** [comment]
Maybe you wanted to add this to koseven? not yclas?

**Comment by mrx** [comment]
Opps, Thanks :)

**Comment by mrx** [comment]
Turns out this is a yclass file.  in oc/classes.

**Comment by neo22s** [comment]
what do you need to do in yclas? it is working fine.

**Comment by mrx** [comment]
I'm using a custom expr. It's a bug in both Koseven and Yclas. 

        $selects = array(); 
        foreach ($this->_db_pending as $key => $method)
        {
            if ($method['name'] == 'select')
            {
                // Ignore any selected columns for now
                $selects[] = $method;  // unordered array
                unset($this->_db_pending[$key]);
            }
        }

Select / expr removed from pending que
>>> $t = [0 => 'one', 1 => 'two'];
=> [
     "one",
     "two",
   ]

Adding the removed "select expr", fails because the key 0 already exists. 
>>> $t += [0 => 'three']
=> [
     "one",
     "two",
   ]

Array merge works
>>> $t = array_merge($t, [0=>'three']);
=> [
     "one",
     "two",
     "three",
   ]
The query builder is smart enough the order removed or added doesn't matter.

**Comment by mrx** [comment]
Looks like Koseven has updated their ORM class to use a key.


				$selects[$key] = $method;  
				unset($this->_db_pending[$key]);

**Comment by neo22s** [comment]
I am asking if this is to use in a yclas project? what's the url? thanks

**Comment by mrx** [comment]
Url isn't public yet. It is a vehicle classifieds.

**Comment by neo22s** [comment]
Do they have already a PRO license?

**Comment by neo22s** [comment]
how do they plan on using all the features?

**Comment by neo22s** [comment]
And?

Did you buy a pro license I am asking and what is the URL.

**Comment by mrx** [comment]
I've answered both of those question.  No, and the URL is private for now. I submitted a fix for an obvious bug. If you want to have a conversation, contact me directly.

**Comment by neo22s** [comment]
https://selfhosted.yclas.com/themes/yclas-self-hosted-pro-1-month.html

**Comment by mrx** [comment]
You want $350 USD to accept bug reports for a month?

**Comment by neo22s** [comment]
This is the PRO license price, one time payment. Please read it. It's clear.
