### ISSUE TITLE
Unable to add a photo when editing an ad!

### ISSUE THREAD

**Issue by wilsden** [yclas/yclas#2825]
With an already published ad, you can not add a photo, just delete it.
The code helped, from the old version 3.5.0
----------------------------------------------------
/themes/olson/views/oc-panel/profil/edit_ad.php
 line 307   
version olson 3.6.0

**Comment by neo22s** [comment]
what's your site domain so we can test?

**Comment by oliverds** [comment]
Sorry but I'm unable to reproduce this issue. Tested uploading additional pictures with Olson theme but no issues.

**Comment by wilsden** [comment]
> какой домен вашего сайта, чтобы мы могли проверить?

shkaf-market.ru

**Comment by neo22s** [comment]
can you send a video or screenshot? thanks

**Comment by wilsden** [comment]
> Вы можете отправить видео или скриншот? Спасибо

https://yadi.sk/i/3KsOghiIiC3iFw
The script is very good! Where can I write my ideas on functionality?

**Comment by oliverds** [comment]
It seems your olson theme is not on version 3.6.0. Yclas 3.6 uses a new image uploader.

You can check your theme version on /themes/olson/init.php source file.

**Comment by wilsden** [comment]
> Похоже, ваша тема олсон не на версии 3.6.0. Yclas 3.6 использует новый загрузчик изображений.
> 
> Вы можете проверить версию своей темы в /themes/olson/init.php исходном файле.

 Version: 3.6.0 Checked!
