### ISSUE TITLE
Dynamically generate example CSV file for import

### ISSUE THREAD

**Issue by oliverds** [yclas/yclas#2828]
We now require additional columns depending on configuration.

https://github.com/oliverds/openclassifieds2/blob/master/oc/classes/controller/panel/import.php#L563

We should also generate an example CSV file if additional options are enabled.

**Comment by neo22s** [comment]
that what I told the customer.... maybe we sohuld also improve the message, saying not same header or similar?

**Comment by oliverds** [comment]
I see it's clear on the docs but not so clear on the import page. We could also throw the expected headers on the error message.
