### ISSUE TITLE
Implement other email delivery systems

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2829]
We only offer SMTP  + elastic email

Check:

- https://www.sparkpost.com/
- https://sendgrid.com/
- https://www.mailgun.com/
- https://postmarkapp.com/
- https://pepipost.com/
- https://sendpulse.com/features/smtp
- https://aws.amazon.com/ses/ (but we will need to do a guide for users to get the key)

**Comment by neo22s** [comment]
After checking  pricing and easiness to implement... we can just recommend services to use SMTP directly xD

-[ ] AWS SES https://docs.aws.amazon.com/ses/latest/DeveloperGuide/smtp-credentials.html
-[ ] Mailgun https://www.mailgun.com/smtp
-[ ] Sendpulse  https://sendpulse.com/prices/smtp

Update the guide:
https://docs.yclas.com/smtp-configuration/

And clearly explain we do not recommend using Gmail outlook etc..

**Comment by neo22s** [comment]
https://github.com/yclas/documentation/pull/388

**Comment by geniusdibya** [comment]
> We only offer SMTP + elastic email
> 
> Check:
> 
> * https://www.sparkpost.com/
> * https://sendgrid.com/
> * https://www.mailgun.com/
> * https://postmarkapp.com/
> * https://pepipost.com/
> * https://sendpulse.com/features/smtp
> * https://aws.amazon.com/ses/ (but we will need to do a guide for users to get the key)

Hi @neo22s, This is Dibya here from Pepipost. Thanks for the mention. 
I would be happy to assist the yclas community here to integrate with Pepipost SMTP. You can directly reach me on dibya(at)pepipost.com

**Comment by neo22s** [comment]
feel free to add it to the docs after SES

https://github.com/yclas/documentation/blob/gh-pages/SMTP-configuration.md
