### ISSUE TITLE
Reflected XSS 

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2834]
Reported by @Sjord 27-02-2019

----------------------------------
Hi Chema,

I found a cross-site scripting security vulnerability in Yclas. When searching for an advertisement the search query is put in the search field, and quotes are not properly encoded here. By searching on the following value, an event handler is attached and executed:

" autofocus onfocus="alert(1)

This is also put in the URL, so by sending someone the following URL it is possible to execute arbitrary JavaScript in his browser in the context of the Yclas application.

http://yclas.local/search.html?title=%22+autofocus+onfocus%3D%22alert%281%29

I tested this on the latest git version of today.

Regards,

Sjoerd Langkemper

-----------------------------------

Fixed same day @ https://github.com/yclas/yclas/commit/f51a1d135d7453659a4ab3b3b320762d7218fafc

**Comment by neo22s** [comment]
@oliverds all good? ;)

**Comment by oliverds** [comment]
Yes. PR pending https://github.com/yclas/yclas/pull/2833 reverts 
https://github.com/yclas/yclas/commit/f51a1d135d7453659a4ab3b3b320762d7218fafc becasue was causing html double encodes and array to string conversion errors; and wraps core::get and core::post with HTML::chars instead.

**Comment by neo22s** [comment]
can we close this?
