### ISSUE TITLE
Facebook Login Button

### ISSUE THREAD

**Issue by oliverds** [yclas/yclas#2835]
Platform Policy 8.3: Use a clearly branded "Login with Facebook" button and follow the Facebook Brand Guidelines: https://www.facebookbrand.com/.
Your Login button doesn't properly reference Facebook. To fix this issue, you should always use our official SDK for Login. For more information on Login best practices, check out the Login section of our developer documents: https://developers.facebook.com/docs/facebook-login/best-practices#buttondesign.

You can access the full list of our Platform Policies here: https://developers.facebook.com/policy/.

Please make the requested changes by 2019-03-10 at 12:00 PST.

Let us know when you've updated your app by replying to this email. If we do not hear back from you, your app will be subject to enforcement. If you have outstanding questions, respond here and we'll do our best to help.

**Comment by Emyoosol** [comment]
> 
> same email received today what to do know how to change my login with facebook button plz help
> Platform Policy 8.3: Use a clearly branded "Login with Facebook" button and follow the Facebook Brand Guidelines: https://www.facebookbrand.com/.
> Your Login button doesn't properly reference Facebook. To fix this issue, you should always use our official SDK for Login. For more information on Login best practices, check out the Login section of our developer documents: https://developers.facebook.com/docs/facebook-login/best-practices#buttondesign.
> 
> You can access the full list of our Platform Policies here: https://developers.facebook.com/policy/.
> 
> Please make the requested changes by 2019-03-10 at 12:00 PST.
> 
> Let us know when you've updated your app by replying to this email. If we do not hear back from you, your app will be subject to enforcement. If you have outstanding questions, respond here and we'll do our best to help.

**Comment by neo22s** [comment]
Please use support ticket system.
