### ISSUE TITLE
Setting - Advertisement Error

### ISSUE THREAD

**Issue by DonPramis** [yclas/yclas#2837]
Hi Guys,

I found this issues on 3.6.0

It's Located in Settings - Advertisement (Just when you click advertisement this error will show)
2019-03-09 13:12:33 --- ERROR: ErrorException [ 8 ]: Undefined index: banned_words_among ~ DOCROOT/themes/default/views/oc-panel/pages/settings/advertisement.php [ 372 ] in /public_html/oc/kohana/system/classes/Kohana/Kohana/Exception.php:110

Thanks

**Comment by DonPramis** [comment]
![GitHub Logo](https://imgsafe.org/image/389d866082)

**Comment by neo22s** [comment]
Hello,

That error is since update to 3.6.0 was not correctly done.

Please check your install or contract the update package we offer.

**Comment by DonPramis** [comment]
Hi @neo22s, What you mean please?

**Comment by DonPramis** [comment]
Can I re-install the Update if possible sorry to ask?

**Comment by neo22s** [comment]
Please open a support ticket

**Comment by DonPramis** [comment]
Hi Chema,

 

I already fix the issue. Thanks
