### ISSUE TITLE
Invisible reCaptcha

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2847]
use Invisible reCaptcha
https://developers.google.com/recaptcha/docs/invisible

should we add an option to use normal recaptcha or invisible?

implement in all forms?

**Comment by oliverds** [comment]
Ok. I think we could have both, checkbox and invisible, but reCaptcha API keys can't be reusable for both options :(

**Comment by neo22s** [comment]
ooops

mmm we create a new config?

**Comment by oliverds** [comment]
Wasn't trivial to make it work with Dropzone uploads and multiple forms on the same page.

**Comment by neo22s** [comment]
ups damn it, I will test it later thanks a lot!

**Comment by neo22s** [comment]
Working great!
