### ISSUE TITLE
ERROR: ErrorException [ 8 ]: tempnam()

### ISSUE THREAD

**Issue by arv187** [yclas/yclas#2852]
Hi, I got a issue when I tried exporting data.
WAMP stack ver: 7.1.27

> ERROR: ErrorException [ 8 ]: tempnam(): file created in the system's temporary directory ~ APPPATH\classes\controller\panel\tools.php [ 193 ] in D:\Program Files\Bitnami\wampstack-7.1.27-0\apache2\htdocs\yclas\oc\kohana\system\classes\Kohana\Kohana\Exception.php:110

I found in tools.php line 93 this entry:
`$output_file = tempnam('/tmp', $file_name);`
and I fixed it with:
`$output_file = tempnam(sys_get_temp_dir(), $file_name);`

Regards!

**Comment by neo22s** [comment]
Thanks! are you using bitnami?

**Comment by arv187** [comment]
> 
> 
> Thanks! are you using bitnami?

Yes, Bitnami WAMP Stack with php v7.1.27

**Comment by neo22s** [comment]
use linux!! ;) much better
