### ISSUE TITLE
unknown modifier "?" in preg_match() . 

### ISSUE THREAD

**Issue by mas1375** [yclas/yclas#2860]
it' appear when wanna save something into the database but it just shows this error in my machine.
 . so which server and the PHP version are suitable for yclas  ??
I'm using its free version, not for commercial purpose and it's not online on the internet.
```none
ERROR: HTTP_Exception_500 [ 500 ]: preg_match(): Unknown modifier '?' ~ APPPATH\kohana\system\classes\Kohana\HTTP\Exception.php [ 17 ] in C:\xampp\htdocs\main_project\agriad.ir\oc\kohana\system\classes\Kohana\Request\Client\Internal.php:114
```

**Comment by neo22s** [comment]
7.0 or higher
