### ISSUE TITLE
Stripe SCA

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2861]
Check if with 3D secure it's enough, review if we need to update the API anyway. Maybe enable the 3D secure option by default ON.

> Strong Customer Authentication (SCA), a new rule coming into effect on September 14, 2019 as part of PSD2 regulation in Europe, will require changes to how your European customers authenticate online payments. Card payments will require a different user experience, namely 3D Secure, in order to meet SCA requirements. Transactions that don’t follow the new authentication guidelines may be declined by your customers’ banks.

**Comment by oliverds** [comment]
Ok. To comply SCA with Stripe, we need to do a [Checkout Migration](https://stripe.com/docs/payments/checkout/migration) because it supports dynamic 3D Secure 2.

**Comment by oliverds** [comment]
Ok. Not everyone needs to accomplish to the new SCA regulation so we can have both Stripe Checkout and Legacy Checkout.

> **Impacted businesses and payments**
You will need to prepare for SCA and update your Stripe integration if **all of the following apply**:
> - Your business is based in the European Economic AreaThe European Economic Area is a regional single market with free movement of labor, goods, and capital. It encompasses the European Union member states and three additional states that are part of the European Free Trade Association. (EEA)
> - You serve customers in the EEA
> - You accept cards (credit or debit)

Also with the Legacy Checkout, we can get a token and make charges with it but with the new Checkout, it's not possible, users always need to go to the Stripe payment page.

**What's was done:**

- Stripe Libary updated to the latest version
- New stripe option to disable legacy mode
- StripeCheckout class to generate Stripe payment buttons
- StripeCheckout controller to process payments

**Comment by neo22s** [comment]
ok, so to understand and test it. If they enable legacy, it's the old one
and they will need it for the recurrent payments, correct?

**Comment by oliverds** [comment]
> ok, so to understand and test it. If they enable legacy, it's the old one and they will need it for the recurrent payments, correct?

Correct :)

**Comment by neo22s** [comment]
ok, seems to be working good! we need to modify the docs to ask to use legacy in case that they want auto renewals correct?

Also implement it for yclas.com classifieds sites.
