### ISSUE TITLE
Unable to login to admin

### ISSUE THREAD

**Issue by liberaxpress** [yclas/yclas#2862]
Hi,

I have just installed the yclas from softaculous and clicked on the admin login link after installation but the username & password I created does not work and it just reloads the login page every time I try to access the admin panel.

Can anyone give me any idea what it can be? I even tried uninstalling and installing again but same problem and set php version to 7.0

Thanks

Liberaxpress

**Comment by neo22s** [comment]
Hello,

What exact error do you get in the error logs?

What's your URL? 

it's your hosting compatible?

**Comment by liberaxpress** [comment]
Hi, thanks for the fast reply. There is no error, the page just refreshes after it attempts to login and I see the same login page.

And how do I check my hosting is compatible? I updated from 5.3 to 7.0 which I read was required and as far as I am aware everything else is fine.

**Comment by neo22s** [comment]
Whats your hosting company and whats your url? 7.0 or higher
