### ISSUE TITLE
Add to Home Screen

### ISSUE THREAD

**Issue by oliverds** [yclas/yclas#2872]
> Add to Home Screen, sometimes referred to as the web app install prompt, makes it easy for users to install your Progressive Web App on their mobile or desktop device. 

https://developers.google.com/web/fundamentals/app-install-banners/

**Comment by neo22s** [comment]
Maybe add a setting to be able to enalbe it or disable it?

**Comment by oliverds** [comment]
> Maybe add a setting to be able to enalbe it or disable it?

Sorry didn't saw your reply before.

Open PR updated.
