### ISSUE TITLE
Subscription::delete_ad()

### ISSUE THREAD

**Issue by oliverds** [yclas/yclas#2884]
**Scenario**

1. User subscribes to a monthly plan with 5 ads.
2. User publishes 5 ads, so no more ads left to publish.
3. User or admin deletes an ad
4. User now has 4 ads but still cannot publish a new ad because subscription amount ads left is 0.

**Expected**
On ad delete, the user should have one more ad left to publish.

**Comment by neo22s** [comment]
If you do this then they can publish unlimited...

**Comment by oliverds** [comment]
Sorry, I meant increase ads_left up to plan ads.

‘min($subscription->ads, $subscription->ads_left++)’

**Comment by neo22s** [comment]
but will happen the same? let talk about it on monday I do not understand it eheheh

**Comment by oliverds** [comment]
Sorry, I thought we also decrease the number of ads left on myads->activate ad.

Anyway, I updated my first post to make clear the situation :)

**Comment by neo22s** [comment]
But still even if user deletes an ad, he should not be able to publish more.

Maybe if admin does yes... since maybe its not fair. But not sure about this, maybe we can make a quick call tomorrow?

**Comment by oliverds** [comment]
> maybe we can make a quick call tomorrow?

Sure! :)
