### ISSUE TITLE
Unable to get user latitude and longitude

### ISSUE THREAD

**Issue by oliverds** [yclas/yclas#2891]
Google now requires an API key to get geocode location through [API calls](https://github.com/yclas/yclas/blob/master/oc/classes/controller/panel/profile.php#L199) but can't be the same as `advertisement.gm_api_key` because that API is restricted by domain referrer.

Perhaps we should integrate a typeahead location, same as on publishing new ad form and be able to use the same `advertisement.gm_api_key` config.

**Comment by neo22s** [comment]
mmm not sure I understand the issue correctly let's chat !

**Comment by oliverds** [comment]
**Currently**

To set user's latitude/latitude, a user goes to profile edit enters an address and on the controller profile, we make an API request on the server side to get latitude/latitude to `http://maps.google.com/maps/api/geocode` (https://github.com/yclas/yclas/blob/master/oc/classes/controller/panel/profile.php#L199). This no longer works without a Google Maps API Key non-referrer restricted.

**Propose**

Get the user's latitude/latitude on the client side, just like on publish new ad :)

<img width="588" alt="Screen Shot 2019-06-25 at 12 20 33" src="https://user-images.githubusercontent.com/7003648/60119378-e90c2100-9743-11e9-92bc-73f25a2d74b0.png">

**Comment by neo22s** [comment]
great!! :D
