### ISSUE TITLE
[30-Jul-2019 17:32:41 America/New_York] PHP Parse error:  syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in ORM.php on line 2279

### ISSUE THREAD

**Issue by Diamondog** [yclas/yclas#2902]
Keep getting this error when trying to work with Yclas:

[30-Jul-2019 17:32:41 America/New_York] PHP Parse error:  syntax error, unexpected '.', expecting '&' or variable (T_VARIABLE) in ORM.php on line 2279

Also when you try to go to the home page of the domain i get this error.. 

![image](https://user-images.githubusercontent.com/14934423/62177617-965df000-b313-11e9-9cb8-4d23032b8e26.png)

What am i doing wrong?

**Comment by neo22s** [comment]
hello,

1. What's your site URL?
2. Can you paste your hosting PHP version, mysql and modules?

**Comment by neo22s** [comment]
Seems your hosting it's not compatible which one is?

**Comment by Diamondog** [comment]
Version # PHP version: 7.2.7

**Comment by neo22s** [comment]
What's your website url. And check the phpinfo something it's missing. You
need to use a compatible hosting.

**Comment by Diamondog** [comment]
WHM with Cpanel access is what I am using

**Comment by Diamondog** [comment]
The website URL is http://cryptoslist.biz/

**Comment by oliverds** [comment]
It seems that your PHP version doesn't support the splat operator.

Please check your PHP version by creating a [phpinfo](https://make.wordpress.org/support/handbook/appendix/creating-a-phpinfo-page/) page.

**Comment by Diamondog** [comment]
I have gotten this far now 
![image](https://user-images.githubusercontent.com/14934423/62255524-86094c00-b3cb-11e9-81da-fef765940239.png)

But cant seem to figure out why PHP and MODrewrite are kicking back to me.. Any ideas?

**Comment by oliverds** [comment]
Please contact your web hosting provider so they can assist you to satisfy yclas server requirements.

**Comment by Diamondog** [comment]
Ok I have gotten this far now. I am not sure what I am getting this : 

![image](https://user-images.githubusercontent.com/14934423/62256644-134e9f80-b3d0-11e9-84d0-85442ac054a6.png)

Not sure what it is looking for , for this information. Is it looking for my domain name as the host name or what?

**Comment by Diamondog** [comment]
This is when it is trying to install I gave it the ID and PW of the DB i created for it

**Comment by neo22s** [comment]
That's the MySQL connection settings. That needs to be provided by your
hosting company.

**Comment by Diamondog** [comment]
This is on my own server.. where would I find that setting?

**Comment by Diamondog** [comment]
I have WHM/Cpanel

**Comment by neo22s** [comment]
It's the connection string. Normally it's localhost. But only you know
that..... We do not know it. What we know is that the software and the
installation works perfectly fine. You fill the data click install and
ready ;)

**Comment by Diamondog** [comment]
ok., Thanks for the help so far.. Now I am getting this message: 

![image](https://user-images.githubusercontent.com/14934423/62257204-60cc0c00-b3d2-11e9-9176-db0ea8f13890.png)
 

But when I click on the GO to website selection it just sits there and does no load.. tries to load but .... Nothing...

**Comment by neo22s** [comment]
Please check the error logs in your server.

**Comment by Diamondog** [comment]
Ok well it just took a little time to load up.. the 1st time.. Thank you for your help everyone.. I will take this thing for a test drive and let you know what i think..

**Comment by Diamondog** [comment]
Now how do i make this so you MUST have a ID and PW to list on the site?

**Comment by neo22s** [comment]
This is not a support forum. Please check docs.yclas.com or you can get any
of our support plans at selfhosted.yclas.com thanks

**Comment by Diamondog** [comment]
ok thank you.. sorry for that.. but thanks for the help!!!
