### ISSUE TITLE
Error Message Not Sent

### ISSUE THREAD

**Issue by Diamondog** [yclas/yclas#2906]
I am getting this message : 

![image](https://user-images.githubusercontent.com/14934423/62340993-8da22100-b4af-11e9-8d6e-cbc9cc476656.png)

When someone is trying to send a message to someone that has listed an item. Can you tell me how to correct this.. Thank you

**Comment by neo22s** [comment]
Please this is not a support forum. Can be due to 2 reasons. Smtp not
configured, or you are trying to write to yourself, which you can't do 😅
