### ISSUE TITLE
table field

### ISSUE THREAD

**Issue by gesaleh** [yclas/yclas#2908]
Hi 
How to create an input field as follow : 
| S | M | L | XL |
| 1 | 3 | 1 | 0 |

first is title list second is number of each item in the list
when I checked list items that exist today custom, it is not far 
need input for each title  

any ideas will be great 

Thanks

**Comment by neo22s** [comment]
Hello! please this is not a support forum, this is meant for developers, to report bugs and technical issues.

For support please go here: https://yclas.com/contact.html
