### ISSUE TITLE
Import Users

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2910]
- [x] Create a CSV file with name, email, plain password (password not added then generate it)
- [x] upload it in the panel
- [x] Create docs and sample CSV

**Comment by neo22s** [comment]
For some reason happens 2 things:

- users get created but the password I have set does not work
- The table usersimport it's not emptied once completed.

**Comment by neo22s** [comment]
ok, I think I figured out.

I had some users already existing in the DB. The password does work when I create new ones.

For some reason, if the user already existed the Table is not emptied:

![image](https://user-images.githubusercontent.com/241725/65224023-a055d100-dac2-11e9-93c1-6dc5b8abbe22.png)

**Comment by oliverds** [comment]
Yep, it's missing empty table when the import process is complete.

> The password does work when I create new ones.

You mean you can't log in with the passwords in CSV file? If a user already exists, the import tool doesn't overwrite the user's password.

**Comment by neo22s** [comment]
all good thanks :D
