### ISSUE TITLE
Video Upload using google drive

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2911]
- [ ] New custom field video
- [ ] using same as upload to google drive
- [ ] we get the video ID
- [ ] Then embed using https://jsfiddle.net/x7npemhz/
- [ ] Check is responsive
- [ ] Create docs

**Comment by neo22s** [comment]
Did you test it in yclas.tk? in local I can  not test it :(

**Comment by oliverds** [comment]
I'm checking it. On local works fine to me but not on .tk :(
