### ISSUE TITLE
there's a bug 3.7.0

### ISSUE THREAD

**Issue by nur-azhar** [yclas/yclas#2925]
there's an annoying bug when i login i dont know how to explain it just have a look here
https://imgur.com/t3cknL4

**Comment by neo22s** [comment]
We will review this, please clean the cache in your borwser and enter again.

**Comment by nur-azhar** [comment]
solved it by pressing end tour when prompt the first time logging in

**Comment by neo22s** [comment]
We will check it anyway. If they click any other place tour should be finished.

**Comment by oliverds** [comment]
The problem is that Google Custom Search Engine is appending "#gsc.tab=0" in URL, so the tour step doesn't match and keeps redirecting.

To solve it I think we need to disable "Results Browsing History" on GCSE (https://techjourney.net/google-custom-search-engine-appends-gsc-tab0-in-url/)

**Comment by neo22s** [comment]
But each person needs to do it in their site? I can do it on yclas.com only

**Comment by oliverds** [comment]
Only our Google Custom Search Engine used for docs search ;)

**Comment by neo22s** [comment]
Maybe better to remove it? I could not even remember we had this xD
