### ISSUE TITLE
PHP 7.3 support

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2932]
https://www.php.net/manual/en/migration73.incompatible.php
https://www.php.net/manual/en/migration73.deprecated.php

**Comment by neo22s** [comment]
ok, tested it and all seems good. @oliverds are you using 7.3 already? yclas.tk using 7.3 too. All good too ;)

**Comment by oliverds** [comment]
Yep. I have been using it with 7.3 for a while without issues.

**Comment by neo22s** [comment]
I had to install few things in yclas.tk and my local, but all perfect! thanks
