### ISSUE TITLE
unable to access settings

### ISSUE THREAD

**Issue by viviane2796** [yclas/yclas#2934]
Every time I try to click on any of the settings within the control panel of YCLAS it just spins and I can't access - general, media settings, advertisement, email settings, plugins, or anything else under that tab. Help please! I'm trying to reconfigure things and they are not showing up. 

Also the free themes are not working correctly. The basecamp free does not resize for mobile. The ocean free seems to not function properly because the category counters are not working.

**Comment by neo22s** [comment]
Hello Viviane,

This is not a support forum its github we use it for issues for developers, for support please use:

https://yclas.com/contact.html

Remember to indicate your url screenshots etc...
