### ISSUE TITLE
PHP 7.4 Support

### ISSUE THREAD

**Issue by oliverds** [yclas/yclas#2942]
I have switched to PHP 7.4, and so far, the only issue I have is related to Kohana Profiling.

![Screen Shot 2019-12-30 at 10 37 48](https://user-images.githubusercontent.com/7003648/71591100-a52e1600-2af0-11ea-95ea-3fb8ffeda8e2.png)

I had to comment that line to make it work, but I'm not sure yet why that error is happening.

**Comment by neo22s** [comment]
We need to check this really good. Also do a PR to koseven once we find how to fix it.

**Comment by oliverds** [comment]
> I have switched to PHP 7.4, and so far, the only issue I have is related to Kohana Profiling.
> 
> ![Screen Shot 2019-12-30 at 10 37 48](https://user-images.githubusercontent.com/7003648/71591100-a52e1600-2af0-11ea-95ea-3fb8ffeda8e2.png)
> 
> I had to comment that line to make it work, but I'm not sure yet why that error is happening.

PHP 7.4.2 fixes this. 😁

**Comment by neo22s** [comment]
Yes I forgot to tell you in koseven forum we have said that 😂
