### ISSUE TITLE
My Settings all menu not working and showing below error 

### ISSUE THREAD

**Issue by jaikeshsinghgithub** [yclas/yclas#2957]
My all page working except setting section page like general setting , payment setting , advertisement and other pages which under setting tab not working and showing below error  

Error1

2020-02-13 00:46:13 --- ERROR: Database_Exception [ 2 ]: mysqli::mysqli(): (HY000/1203): User ads4wo6_open578 already has more than 'max_user_connections' active connections ~ APPPATH/kohana/modules/database/classes/Kohana/Database/MySQLi.php [ 75 ] in /home/ads4wo6/public_html/oc/kohana/system/classes/Kohana/Kohana/Exception.php:110

Error 2

SplFileInfo::openFile(/home/ads4wo6/public_html/oc/cache/2f/2f2a56fa46b8720e64b67ff041b9f2c6dddcd009.cache): failed to open stream: No such file or directory ~ APPPATH/classes/cache/file.php [ 42 ] in /home/ads4wo6/public_html/oc/kohana/system/classes/Kohana/Kohana/Exception.php:110
2020-02-13 17:36:40 --- ERROR: RuntimeException [ 0 ]: 

![image](https://user-images.githubusercontent.com/31641221/74502679-43950000-4f14-11ea-811a-fdfe7b35db17.png)

**Comment by jaikeshsinghgithub** [comment]
my domain name is ads4world.com

**Comment by neo22s** [comment]
Hello,

Those 2 errors are hosting errors. contact your hosting company.

We only accept issues that are bug reports or feature requests. Bugs must be isolated and reproducible problems that we can fix within the Yclas core. Please read the following guidelines before opening any issue.

    Search for existing issues. We get a lot of duplicate issues, and you'd help us out a lot by first checking if someone else has reported the same issue. Moreover, the issue may have already been resolved with a fix available.
    Create an isolated and reproducible test case. Be sure the problem exists in Yclas code.
    Include a live example. Make use of screenshots if needed.
    Share as much information as possible. Include operating system and version, browser and version, version of OC, customized or vanilla build, etc. where appropriate. Also include steps to reproduce the bug.
