### ISSUE TITLE
Locations import examples

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2970]
Hosted in github docs?

Global / all countries
per country? main states and cities.

**Comment by neo22s** [comment]
Current geoname import it's not really nice. maybe improve functionality and create a queue to download all child locations?

Other solutions:

https://gis.stackexchange.com/questions/21923/seeking-comprehensive-list-of-latitude-and-longitude-values-for-cities-around-wo
https://wiki.openstreetmap.org/wiki/API_v0.6
https://wiki.openstreetmap.org/wiki/Planet.osm#Downloading

**Comment by neo22s** [comment]
We can use the open source from osclass

https://www.valueweb.gr/forums/osclass-geo-data-files/

We import them into the 2 tables cities and regions. We standardize it into 1 unique table called locations.

**Comment by oliverds** [comment]
So, it would be better to import locations (regions, cities) per country with a single click or so?

**Comment by neo22s** [comment]
Yes like 1 click and then all the locations below... the problem is that geonames adds many between..

**Comment by oliverds** [comment]
Got it! 👍 

It would no be possible with Geonames because of their strict API rate limits on the free version.

So maybe we could generate a .sql file per country and store it in Github with all the locations and fetch the SQL with the location import tool.

**Comment by neo22s** [comment]
I think is the best... as osclass was doing... we have part of the work
done thanks to them. We need to create a script that reads their files and
addapts it ;)

**Comment by oliverds** [comment]
Ok. I generate an adapted .sql file per country.

Should we have them in another repository or inside Yclas?

**Comment by neo22s** [comment]
Wow!! nice!!

Yes we can put them in https://github.com/yclas/geo 

And maybe store there a JSON file like https://github.com/yclas/geo/blob/master/countries.json

So we can use it from a CDN like https://cdn.jsdelivr.net/gh/yclas/geo@master/countries.json

**Comment by neo22s** [comment]
He probado de poner el de españa y me da un error:

INSERT INTO `oc2_locations` (`id_location`, `name`, `order`, `id_location_parent`, `parent_deep`, `seoname`, `description`, `last_modified`, `has_image`, `latitude`, `longitude`, `id_geoname`, `fcodename_geoname`, `translation_name`, `translations`)


MySQL said: Documentation
#1054 - Unknown column 'translation_name' in 'field list'

**Comment by oliverds** [comment]
¡Ups! Tendré que arreglar los .sql parece que tenía una columna huérfana en mi bd local cuando desarrollamos lo de la traducción de categories y locations
