### ISSUE TITLE
open graph images size

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2975]
In header_metas.php

We use controller::$image 

`<meta property="og:image"   content="<?=Controller::$image?>"/>
`

we need to use a larger image file

customer:
> I use a service called Dlvrt.it that shares the RSS feed to my facebook groups. The only problem is that when the ad automatically post it mixes up the pictures sometimes. So an ad will show up but with a different ads picture.  
> I asked them about it and they said:I've checked over your Facebook posts and it looks like your images are not being retrieved due to their sizing. They appear to be too small for Facebook to use, so they appear to be choosing their own images from that page. The best method to fix this would be to update your Open Graph images to be larger. Our recommended minimum dimensions are 400x300. However, in Facebook, square images are more effective. Your web development team should be able to assist with this.
> Have you had any issues like this or is there a different company you would recommend?

**Comment by oliverds** [comment]
Ok, we should use the full listing image instead.
