### ISSUE TITLE
Virtual Wallet / Coin

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#2989]
**Virtual Coin**  

*   coin transaction (from,to, id\_order, coins)
*   they can move money between users
*   to top up, featured ....
*   how to buy coins -- create plans like featured ads
*   Gamification, setting On sign up -- XXX coins
*   pay for products of users (mark product as received after X days, cron remember to mark as received after X days)

**Comment by neo22s** [comment]
ewallet

**Comment by oliverds** [comment]
Guide: https://guides.yclas.com/#/e-wallet

**Comment by neo22s** [comment]
some feedback:

/oc-panel/integrations
![image](https://user-images.githubusercontent.com/241725/105048139-825c0000-5a6b-11eb-8b9f-966126e5d533.png)

A eWallet system
Replace with
An eWallet system for your marketplace.

My Transactions using  Basecamp premium displays full widht
http://reoc.lo/oc-panel/ewallet
![image](https://user-images.githubusercontent.com/241725/105048681-1d54da00-5a6c-11eb-831c-088573c64cdb.png)

**Comment by neo22s** [comment]
error /ad/checkout/209

Stripe\Error\InvalidRequest [ 0 ]: Invalid currency: ycl. Stripe currently supports these currencies: usd, aed, afn, all, amd, ang, aoa, ars, aud, awg, azn, bam, bbd, bdt, bgn, bhd, bif, bmd, bnd, bob, brl, bsd, bwp, bzd, cad, cdf, chf, clp, cny, cop, crc, cve, czk, djf, dkk, dop, dzd, egp, etb, eur, fjd, fkp, gbp, gel, gip, gmd, gnf, gtq, gyd, hkd, hnl, hrk, htg, huf, idr, ils, inr, isk, jmd, jod, jpy, kes, kgs, khr, kmf, krw, kwd, kyd, kzt, lak, lbp, lkr, lrd, lsl, mad, mdl, mga, mkd, mmk, mnt, mop, mro, mur, mvr, mwk, mxn, myr, mzn, nad, ngn, nio, nok, npr, nzd, omr, pab, pen, pgk, php, pkr, pln, pyg, qar, ron, rsd, rub, rwf, sar, sbd, scr, sek, sgd, shp, sll, sos, srd, std, szl, thb, tjs, tnd, top, try, ttd, twd, tzs, uah, ugx, uyu, uzs, vnd, vuv, wst, xaf, xcd, xof, xpf, yer, zar, zmw, eek, lvl, svc, vef, ltl

**Comment by neo22s** [comment]
Add money does not appear  Basecamp premium 
http://reoc.lo/oc-panel/ewallet

**Comment by neo22s** [comment]
How do I buy an item from a user? the buy button does not appear.

**Comment by oliverds** [comment]
- Changed copy to "An eWallet system for your marketplace."
- Fixed basecamp transactions layout.

> How do I buy an item from a user? the buy button does not appear.

Uses the same config as "Buy now", but added the config on the eWallet add-on settings page.

> Add money does not appear in any theme

It seems ok to me. "Add money" config is enabled?

> error /ad/checkout/209
> 
> Stripe\Error\InvalidRequest [ 0 ]: Invalid currency: ycl. Stripe currently supports these currencies: usd, aed, afn, all, amd, ang, aoa, ars, aud, awg, azn, bam, bbd, bdt, bgn, bhd, bif, bmd, bnd, bob, brl, bsd, bwp, bzd, cad, cdf, chf, clp, cny, cop, crc, cve, czk, djf, dkk, dop, dzd, egp, etb, eur, fjd, fkp, gbp, gel, gip, gmd, gnf, gtq, gyd, hkd, hnl, hrk, htg, huf, idr, ils, inr, isk, jmd, jod, jpy, kes, kgs, khr, kmf, krw, kwd, kyd, kzt, lak, lbp, lkr, lrd, lsl, mad, mdl, mga, mkd, mmk, mnt, mop, mro, mur, mvr, mwk, mxn, myr, mzn, nad, ngn, nio, nok, npr, nzd, omr, pab, pen, pgk, php, pkr, pln, pyg, qar, ron, rsd, rub, rwf, sar, sbd, scr, sek, sgd, shp, sll, sos, srd, std, szl, thb, tjs, tnd, top, try, ttd, twd, tzs, uah, ugx, uyu, uzs, vnd, vuv, wst, xaf, xcd, xof, xpf, yer, zar, zmw, eek, lvl, svc, vef, ltl

For what product was /ad/checkout/209.
