### ISSUE TITLE
Panel Yclas 4

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#3001]

**Comment by neo22s** [comment]
Some feedback:

*   [ ] When I am in the panel I can not go back to the dashboard
*   [ ] We need to improve the ajax tables views, we will discuss this
*   [ ] When I click in advertisement  "Invalid argument supplied for foreach() ~ DOCROOT/themes/default/views/oc-panel/pages/ad.php \[ 148 \]" if there's no ads.
*   [ ] change theme does not work gets stuck in default
*   [ ] /oc-panel/user does not load

**Comment by oliverds** [comment]
- [ ] Profile dropdown to logout
- [ ] /oc-panel/map wrong layout

**Comment by oliverds** [comment]
> * Not loading user data /oc-panel/user

@neo22s It looks ok to me on http://400.yclas.tk/oc-panel/user

<img width="1517" alt="Screen Shot 2020-06-11 at 09 57 53" src="https://user-images.githubusercontent.com/7003648/84402489-19a1d080-abca-11ea-9f24-8906a2822c99.png">

**Comment by neo22s** [comment]
addblock disabled maybe the issue is in firefox? chrome loads correct :S

![](https://user-images.githubusercontent.com/241725/84404331-f8aba080-ac06-11ea-9c3a-285a3798fa17.png)

![](https://user-images.githubusercontent.com/241725/84404405-0eb96100-ac07-11ea-8c98-d59ea8ecdb21.png)

**Comment by oliverds** [comment]
Weird. Tested on Firefox and looks ok to me too.

Could you please expand the SyntaxError: JSON.parse ... ?

**Comment by neo22s** [comment]
```
SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data jquery.bootgrid.min.js:6:2671
   jQuery 5
       success
       c
       fireWith
       l
       o
```

**Comment by neo22s** [comment]
![](https://user-images.githubusercontent.com/241725/84562475-1ab33900-ad55-11ea-9ec1-a47de526724f.png)

Fix copy

https://400.yclas.tk/oc-panel/addons/sociallogin# add the help menu

**Comment by oliverds** [comment]
**Add link to guides** (http://guides.yclas.com)

- [ ] Manage
- [ ] Content
- [ ] Configure
- [ ] Tools

**Comment by neo22s** [comment]
Excel to see URLs and guides https://docs.google.com/spreadsheets/d/1XLF9H01mHnm-gLYcB6vIaGZJdzBvT2U_4h6hEz65_SQ/edit#gid=0

**Comment by neo22s** [comment]
Excel to see URLs and guides https://docs.google.com/spreadsheets/d/1XLF9H01mHnm-gLYcB6vIaGZJdzBvT2U_4h6hEz65_SQ/edit#gid=0
