### ISSUE TITLE
My website became completely unaccessible. Even the Admin page.

### ISSUE THREAD

**Issue by crolidge** [yclas/yclas#3011]
I am not sure but I think I have a similar problem.

My website at https://vagas.com.pt/ is completely unavailable.
Even the login page to the Admin dashboard is not accessible.

I haven't done anything for several days. The last time I logged to the Admin dashboard was about 2 weeks ago when I input the Google Maps API key.
Everything was going well, and now suddenly comes the following jumbotron dialog:

**Sorry!
Something went wrong with your request. This incident is logged and we are already notified about this problem.
You can go Back or to our Home page.**

What should I do now? Were you really notified of this trouble?
I haven't bought a license yet. I was about to do it, but how can I pay for it if even the free version of YClas fails like this?

Can you please help me out with this problem and present a solution?
Thanks in advance

![imagem](https://user-images.githubusercontent.com/60101029/84896046-26776600-b09b-11ea-86c8-e66e26af6ae5.png)

**Comment by neo22s** [comment]
Hello,

Have you checked in your hosting log errors? https://docs.yclas.com/error-troubleshooting-wow-seems-error/

that error it's from your hosting company.

Also please open a support ticket and a technician will help you. This is not the correct place for support, we use it for developers.

thanks.

**Comment by crolidge** [comment]
Hi neo22s,

How can I open a support ticket ? Where should I do it? I thought this was the right place.
I cannot even access the Admin.
I have checked the boostrap.php file, made that change, and found the attached errors.
How can I open a ticket?

cheers,

**Comment by crolidge** [comment]
OK, I tried to open a ticket on the website, but I just found I am not entitled to support since I haven't bought a pro plan!!
How is that possible?!
I cannot buy firsta plan in the dark for something that doesn't work fromthe beginning!

Can you give me some pointers here? My errors list is here:
[list of errors.docx](https://github.com/yclas/yclas/files/4792692/list.of.errors.docx)

**Comment by crolidge** [comment]
Thanks a lot my friend. I think I updated the wrong PHP version of the domain. I am in touch with Support now...
