### ISSUE TITLE
update yclas 3.4.0 to 4.0.2 following the docs broke the page

### ISSUE THREAD

**Issue by Don-Ron** [yclas/yclas#3066]
I am running a Yclas 3.4.0 for a client.
I need to update to latest to start making changes afterwards.

When trying to update the page, following the documentation like mentioned [here](https://guides.yclas.com/#/Yclas-self-hosted-installation-how-to-update?id=manual-update) manually from 3.4.0 to 4.0.2 I am getting following effects:

1. cant access the page or panel anymore, as it is showing the error seen in the image below.
2. getting error in the logs.

Details:
![image](https://user-images.githubusercontent.com/22054372/92937315-79b74580-f44b-11ea-97c8-07d881f66abe.png)

and in the error log:

2020-09-11 16:26:16 --- ERROR: View_Exception [ 0 ]: The requested view oc-panel/layouts/master could not be found ~ APPPATH/classes/view.php [ 98 ] in /srv/httpd/domain.com/oc/kohana/system/classes/Kohana/Kohana/Exception.php:110

The Theme used is named Titi (Ocean).

Questions:
How can I update this particular version to the latest version in a proper way?
Were the Themes undergoing braking changes from 3.x to 4.x ?

**Comment by neo22s** [comment]
Hello,

Please this is not a support forum. For any help please visit https://yclas.com/contact.html open a support ticket or reach us by email.

1- using https://guides.yclas.com/#/Yclas-self-hosted-installation-how-to-update?id=manual-update it's how we have updated all customers sites, from any version. Not any problem so far.

2- Yes they are not compatible. You need to have latest Pro version, we sent an email explaining this.

As mentioned before reach us or please follow our contibution guides https://github.com/yclas/yclas/blob/master/CONTRIBUTING.md#reporting-issues
