### ISSUE TITLE
Message responses on ads are empty

### ISSUE THREAD

**Issue by yamamushi** [yclas/yclas#3075]
Using the atlantic-lite theme (I haven't tested the others), whenever I select "Send Message" to respond to an ad, the recipient only ever receives a blank message from me.

If I contact a user directly through their profile page, the messages are working as expected. 

Curiously, if I include a price with the ad response, the price value does appear in the message the recipient receives, but the currency symbol is also wrong (it always defaults to the $ symbol). Regardless, the message is always empty.

**Comment by neo22s** [comment]
Hello,

We need your URL, screenshots etc... remember github it's for only reporting bugs please see our contribution guidelines:

https://github.com/yclas/yclas/blob/master/CONTRIBUTING.md

We only accept issues that are bug reports or feature requests. Bugs must be isolated and reproducible problems that we can fix within the Yclas core. Please read the following guidelines before opening any issue.

1.  **Search for existing issues.** We get a lot of duplicate issues, and you'd help us out a lot by first checking if someone else has reported the same issue. Moreover, the issue may have already been resolved with a fix available.
2.  **Create an isolated and reproducible test case.** Be sure the problem exists in Yclas code.
3.  **Include a live example.** Make use of screenshots if needed.
4.  **Share as much information as possible.** Include operating system and version, browser and version, version of OC, customized or vanilla build, etc. where appropriate. Also include steps to reproduce the bug.

**Comment by yamamushi** [comment]
The URL for this site is -> https://dual.market/

Navigating to an ad, for example: https://dual.market/ore/wanted-25kl-lithium-pure.html , with the contact form enabled on ads there is a send message button that causes the contact form to pop up: 

<img width="563" alt="Screen Shot 2020-10-06 at 2 28 51 PM" src="https://user-images.githubusercontent.com/1475105/95250990-7e6be100-07e0-11eb-8d23-6f5b2a4ad8c6.png">

Typing anything into this form and clicking "Contact Us" results in a blank message being sent to the recipient (images attached)

<img width="1153" alt="Screen Shot 2020-10-06 at 2 29 42 PM" src="https://user-images.githubusercontent.com/1475105/95250992-7f047780-07e0-11eb-9973-015295ee2fea.png">
<img width="1163" alt="Screen Shot 2020-10-06 at 2 30 05 PM" src="https://user-images.githubusercontent.com/1475105/95250994-7f9d0e00-07e0-11eb-8301-ad9372fdce4c.png">
<img width="1163" alt="Screen Shot 2020-10-06 at 2 30 11 PM" src="https://user-images.githubusercontent.com/1475105/95250995-7f9d0e00-07e0-11eb-8877-1719f077da3f.png">
 

I've tried with Chrome, Firefox and Safari to no avail.

I'm using commit e76db8801508f41f9b50995a686545481c6146e2 for this site.

This is a customized site in that I've added a new currency (as this was created for a gaming group where $'s don't exist). Coincidentally, whenever I attach a price to any message, the price does appear in the recipients inbox although still without a message (And the currency symbol is wrong): 

![Uploading Screen Shot 2020-10-06 at 2.34.33 PM.png…]()

**Comment by neo22s** [comment]
Hello,

Please aquire a PRO license to get 1 year support that way we can help you and you help us to keep the development going. Also  you can remove the footer with our license (which you have already done it).
