### ISSUE TITLE
Advertisement counts are wrong

### ISSUE THREAD

**Issue by yamamushi** [yclas/yclas#3076]
On the homepage where categories are listed, each category has a count next to it indicating how many ads are active for it.

However, only the top sub-categories are actually updating with the correct values. If I create an advertisement in a subcategory it never updates the count values displayed.

**Comment by neo22s** [comment]
Hello,

Please this is not the place to get customer support, its for bug reporting. You need to clear the cache of your site.

We need your URL, screenshots etc... remember github it's for only reporting bugs please see our contribution guidelines:

[https://github.com/yclas/yclas/blob/master/CONTRIBUTING.md](https://github.com/yclas/yclas/blob/master/CONTRIBUTING.md)

We only accept issues that are bug reports or feature requests. Bugs must be isolated and reproducible problems that we can fix within the Yclas core. Please read the following guidelines before opening any issue.

1.  **Search for existing issues.** We get a lot of duplicate issues, and you'd help us out a lot by first checking if someone else has reported the same issue. Moreover, the issue may have already been resolved with a fix available.
2.  **Create an isolated and reproducible test case.** Be sure the problem exists in Yclas code.
3.  **Include a live example.** Make use of screenshots if needed.
4.  **Share as much information as possible.** Include operating system and version, browser and version, version of OC, customized or vanilla build, etc. where appropriate. Also include steps to reproduce the bug.
