### ISSUE TITLE
Require login to contact

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#3082]
This text it's a wrong description, actually does not let you see the ads. review this works like this in all themes

/oc-panel/settings/advertisement

replace with:

Require login to view ad

Require only logged in users to see the ad details

![](https://user-images.githubusercontent.com/241725/96755571-2c77ad80-13d3-11eb-9ab9-29d025add7a0.png)

**Comment by oliverds** [comment]
> review this works like this in all themes

"Login to view ad" is checked in the controller https://github.com/yclas/yclas/blob/master/oc/classes/controller/ad.php#L355

**Comment by oliverds** [comment]
I reviewed it again. Actually we do have both settings, `login_to_view_ad` and `login_to_contact` settings, but `login_to_contact` was missing on the advertisement setting page on the new panel design. 😆

**Comment by neo22s** [comment]
Hehehe no problem! Already fixed. Thanks
