### ISSUE TITLE
Location fuzzy search on advanced search page

### ISSUE THREAD

**Issue by oliverds** [yclas/yclas#3087]
Currently we limit to 200 the number of location options to show on the advanced search page, but some users may have more locations and the options get truncated.

Implement a fuzzy search feature could solve this issue. Show a normal select if there are up to _x_ locations, and a _fuzzy search_ select if more.

**Comment by neo22s** [comment]
We need to do this also for location widget.

**Comment by neo22s** [comment]
Works Great!!! 

Only issue I find is that if we search for a region and has a city with same name appears duplicated and we do not know which we sohuld choose. Maybe Put

 Zaragoza

Zaragoza / Zaragoza 

Zaragoza / Casetas (this way they know Casetas is from zaragoza?)

Or similar? nor sure if then they will understand either :S

![](https://user-images.githubusercontent.com/241725/98436026-1c9ce080-20d8-11eb-8127-07970bdd6155.png)

**Comment by oliverds** [comment]
Fixed. I think "Location name, Location parent name" is the most conventional way to do it :)
