### ISSUE TITLE
Custom Orders

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#3113]
The buyer fills in a description and the seller gives a price that is paid at checkout. Using the chat.

**Comment by neo22s** [comment]
great!! can we do docs? so I can test ;)

**Comment by oliverds** [comment]
> great!! can we do docs? so I can test ;)

Sure!

https://guides.yclas.com/#/Plugins-message-system?id=custom-orders

**Comment by neo22s** [comment]
Works good!!
testing in pre ;)
