### ISSUE TITLE
Captcha not working via "Contact form" with Atlantic Lite on 4.0.2

### ISSUE THREAD

**Issue by yclastester** [yclas/yclas#3117]
Testing out 4.0.2 and run into issue when using "Send Message" / Contact form from ad page using Atlantic Lite theme, works fine with Basecamp free theme. See screenshots.

Not sure if this is related to config or bug in theme.

_Using Atlantic Lite theme_

![Screenshot_2020-12-19 Publish new advertisement 2 - Apartment (Housing) - Yclas(4)](https://user-images.githubusercontent.com/76259798/102695082-75a67b00-4225-11eb-9131-01eb5833d303.png)

![Screenshot_2020-12-19 Publish new advertisement 2 - Apartment (Housing) - Yclas(1)](https://user-images.githubusercontent.com/76259798/102695014-18122e80-4225-11eb-83aa-0708b1ed70f1.png)

_Using Basecamp free theme_

![Screenshot_2020-12-19 Publish new advertisement 2 - Apartment (Housing) - Yclas(2)](https://user-images.githubusercontent.com/76259798/102695017-1ba5b580-4225-11eb-94da-04ab68862811.png)

![Screenshot_2020-12-19 Publish new advertisement 2 - Apartment (Housing) - Yclas(3)](https://user-images.githubusercontent.com/76259798/102695019-1ea0a600-4225-11eb-8233-c198ef7e088a.png)

**Comment by neo22s** [comment]
Hello,

What's your webstie url? what's your name?

**Comment by yclastester** [comment]
> 
> 
> Hello,
> 
> What's your webstie url? what's your name?

Hi, there.

Not sure how my name is related to this issue :)

The test site and self-hosted version can be found on following link.
https://yclas.zzz.hemsida.eu/

The setup is a clean install with two accounts each with one ad, and the "Captcha not correct" shows when sending a message via ad page.

**Comment by neo22s** [comment]
Hello,

I like to know exactly with who I am speaking. I doubt your name is @yclastester .

That's all and I think it's pretty normal...

**Comment by yclastester** [comment]
> Hello,
> 
> I like to know exactly with who I am speaking. I doubt your name is @yclastester .
> 
> That's all and I think it's pretty normal...

I am not active on Github and had to create an account to submit this issue here.
Using a nickname is a common practice for online accounts and i picked one in ranom. 
Seem to be a normal thing even among the contributors for this project.

My name is Tomas if that helps this issue.

**Comment by yclastester** [comment]
@neo22s Thanks, the fix in themes `_contact-form.php ` solved the issue with captcha.

Found other issue where messages from the contact form are not included, again with "Atlantic Lite" theme, should i start a new issue or just include it here?

**Comment by neo22s** [comment]
Hello,

Yes please, remember also that we offer 24/7 support in our panel, you can create the issue and a PR with the fix for the issue, that's what we use github for.

**Comment by oliverds** [comment]
> Found other issue where messages from the contact form are not included, again with "Atlantic Lite" theme, should i start a new issue or just include it here?

That issue has been addressed in https://github.com/yclas/yclas/commit/e53dcf9485e018233cd2c136da73e1c3a54ae83c
