### ISSUE TITLE
"Private Site" fature not working in Atlantic theme

### ISSUE THREAD

**Issue by yclastester** [yclas/yclas#3121]
Found many issues with the Atlantic theme, maybe Basecamp should be default till Atlantic is more stable?

![Screenshot_2020-12-23 An error '(](https://user-images.githubusercontent.com/76259798/103017268-a5b28e80-4543-11eb-8809-f49bde5e3e56.png)

**Comment by neo22s** [comment]
Please Bugs must be isolated and reproducible problems that we can fix within the Yclas core. Please read the following guidelines before opening any issue.

    Search for existing issues. We get a lot of duplicate issues, and you'd help us out a lot by first checking if someone else has reported the same issue. Moreover, the issue may have already been resolved with a fix available.
    Create an isolated and reproducible test case. Be sure the problem exists in Yclas code.
    Include a live example. Make use of screenshots if needed.
    Share as much information as possible. Include operating system and version, browser and version, version of Yclas, customized or vanilla build, etc. where appropriate. Also include steps to reproduce the bug.

**Comment by oliverds** [comment]
This is a know bug that has been addressed a few days ago in https://github.com/yclas/yclas/commit/5891df4b88902d374b7f7cca0b181345f45a76f3.

**Comment by yclastester** [comment]
> Please Bugs must be isolated and reproducible problems that we can fix within the Yclas core. Please read the following guidelines before opening any issue.
> 
> ```
> Search for existing issues. We get a lot of duplicate issues, and you'd help us out a lot by first checking if someone else has reported the same issue. Moreover, the issue may have already been resolved with a fix available.
> Create an isolated and reproducible test case. Be sure the problem exists in Yclas code.
> Include a live example. Make use of screenshots if needed.
> Share as much information as possible. Include operating system and version, browser and version, version of Yclas, customized or vanilla build, etc. where appropriate. Also include steps to reproduce the bug.
> ```

> This is a know bug that has been addressed a few days ago in [5891df4](https://github.com/yclas/yclas/commit/5891df4b88902d374b7f7cca0b181345f45a76f3).

Sorry to be a nag posting know issues here.

Before posting i search for "Private Site" and browsed through several old issues from 2016-2017 most related to "request access" issues.

Didn't realised the "Atlantic theme: fix 403 page." was a fix to the Private Site issue.

I also spent some tine looking through the php code, trying to find a solution on my own based on the previous issues and findings.
Note, i have 0 knowledge of php coding.

I will stay away from posing here.

I am testing out the free self hosted version and i'm not sure if there is any other way to reach out to you or find a way to make things work that i find broken. The documentation is very limited on that front.
I'm happy to contribute with documentation.

Maybe you could just set up a Yclas demo site with the forum function enabled so users can share the findings and solutions directly on the site?

**Comment by neo22s** [comment]
Hello,

For testing we have yclas cloud, 15 free trial. Then you have free support too

Please see our website https://yclas.com/contact.html

**Comment by yclastester** [comment]
> Hello,
> 
> For testing we have yclas cloud, 15 free trial. Then you have free support too
> 
> Please see our website https://yclas.com/contact.html

Thank you for the link.

I am planing to self host for a small project so testing on own cloud environment makes more sense i this case.
