### ISSUE TITLE
Atlantic Theme not showing the messaging icon for chat with sellers option

### ISSUE THREAD

**Issue by jadecoyacot123** [yclas/yclas#3141]
Hello Oliver, 

The Atlantic theme is not showing the messaging icon for chat with sellers option. 
I tried using CZ and it worked. Please check attachment. 

![download (24)](https://user-images.githubusercontent.com/66590860/105443060-dc480a00-5ca5-11eb-916b-57a1a9476a0c.png)
![download (34)](https://user-images.githubusercontent.com/66590860/105443061-dd793700-5ca5-11eb-9c9d-1b553e1a9392.png)

**Comment by oliverds** [comment]
Fixed. Thanks for reporting it.
