### ISSUE TITLE
Email must contain a valid email domain

### ISSUE THREAD

**Issue by benwul** [yclas/yclas#3143]
I just installed the selfhosted lite verison 4.1
After successful install I want to login with admin mail: info@xxxx123.com but I'm getting the error:
![image](https://user-images.githubusercontent.com/44745637/105686937-23c5d480-5ef8-11eb-9cd5-fbbf69c67557.png)

**Comment by neo22s** [comment]
The domain name xxxx123.com is valid email domain? please read the error

**Comment by benwul** [comment]
Yes. It is.

**Comment by benwul** [comment]
for instance check24.de
