### ISSUE TITLE
Pinterest Steps Changed.

### ISSUE THREAD

**Issue by jadecoyacot123** [yclas/yclas#3157]
Hello Guys,

It appears that generating API key with Pinterest has been deprecated. Please see attachment
![download - 2021-02-20T111045 477](https://user-images.githubusercontent.com/66590860/108591090-c65f5f00-73a1-11eb-86ef-dbed098b17ae.png)

**Comment by neo22s** [comment]
maybe we need to remove it @oliverds  :(
