### ISSUE TITLE
Advertisement data lost when captcha is incorrect

### ISSUE THREAD

**Issue by maxxo** [yclas/yclas#3159]
When creating a new advertisement, fill out all data title, price, description, location, etc. Then go to enter the captcha, enter the wrong captcha and get error saying wrong captcha and all data entered for the advertisement is gone. So all advertisement info must be entered all over again. Is there a setting that we're missing here to avoid this?

**Comment by neo22s** [comment]
Hello,

Github issues it's meant for developers reporting bugs with a PR that fixes
the bug. We have a support system for any questions you may have.

What's your website URL?

**Comment by maxxo** [comment]
Sorry, just testing out, no URL available. Although this issue seems worth investigating further. What is the support URL for open source self-host users? Paid support URL won't fly. Thanks.

**Comment by neo22s** [comment]
For testing purposes we have a free cloud trial for 15 days, no card
required. Includes free support.
https://yclas.com/create-website.html?plan=free

We do not offer free support for free self-hosted.
