### ISSUE TITLE
Imported locations are not in alphabetical order

### ISSUE THREAD

**Issue by maxxo** [yclas/yclas#3160]
For example, importing states for United States, the states are not imported into alphabetical order. Also the cities for each state are not imported into alphabetical order. So unless admin uses (time consuming) method of drag-drop reorder of locations, then the user sees a non-alphabetical order of locations when they select locations drop-down when creating an advertisement/listing.

**Comment by neo22s** [comment]
Hello,

Github issues it's meant for developers reporting bugs with a PR that fixes
the bug. We have a support system for any questions you may have.

What's your website URL?
