### ISSUE TITLE
2fa.api-docs integration

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#3172]
We need to integrate 2-factor authentication and transactional SMS.

2auth
https://2fa.api-docs.io/v1/send-transactional-sms/transactional-sms-api-2factor-send-sms

Transactional SMS
https://2fa.api-docs.io/v1/send-sms-otp/check-sms-otp-balance

There will be 3 messages.
Please see the messages below,

- [ ]     Dear Customer, We have received your payment. Your premium account will be active shortly. (Notification for the customer once he makes the payment for a subscription)
- [ ]     Dear Customer, Your premium account is going to expire in 2 days. Please renew it to keep premium features active. (Notification for the customer when the account is about to expire)
- [ ]     Dear Customer, We have received your payment. Your requested service will be active shortly. (Notification is for the feature ads)

**Comment by oliverds** [comment]
- [ ] Two-Step SMS Authentication
- [ ] Transactional SMS
- [ ] Create guide

**Comment by neo22s** [comment]
looks great!!! :D

**Comment by neo22s** [comment]
I can close this issue correct?
