### ISSUE TITLE
New google analytics code

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#3178]
maybe we should remove the current implementation and customers needs to paste the HTM in header...

"The API code of google analytics has changed. you will see that your integration does not work with the new google analytics api key. It is however still possible to create the old api key but this feature is now hidden by google by default. I just wanted to share this with you."

**Comment by oliverds** [comment]
Guide updated to use Google Analytics Tag instead.

https://github.com/yclas/guides/commit/50b790145f63f4ab10d10c1bb420406752c12ac1
