### ISSUE TITLE
Instagram Custom Field

### ISSUE THREAD

**Issue by oliverds** [yclas/yclas#3183]
Use an ad or user custom field to add Instagram feed on the single ad page.

Instagram Feed without access token:

https://www.sowecms.com/demos/jquery.instagramFeed/index.html

**Comment by neo22s** [comment]
If no ad CF for instagram uses the one from the User. create docs ;)

**Comment by oliverds** [comment]
- [x] Implementation
- [ ] Guide

**Comment by oliverds** [comment]
Guide: https://guides.yclas.com/#/custom-field-instagram
