### ISSUE TITLE
Twitter configuration not working in dev apps

### ISSUE THREAD

**Issue by jadecoyacot123** [yclas/yclas#3186]
When integrating this guide, I am not able to successfully integrate it due to the fact that twitter has changed their dev app settings.

https://guides.yclas.com/#/Twitter

On the old dev apps, website is required. But on new one, it does not have this option just the token and integration.

This is the Twitter login details: https://twitter.com/Yclas1
Username : testingonlytesttest@gmail.com

![download - 2021-04-09T110457 165](https://user-images.githubusercontent.com/66590860/114260987-a1cf4d00-9a0a-11eb-8a1d-bb4e112eb6dc.png)
![download - 2021-04-09T110445 921](https://user-images.githubusercontent.com/66590860/114260988-a3007a00-9a0a-11eb-8227-20cbe7f4e184.png)

**Comment by oliverds** [comment]
I'm unable to access to the Twitter test account:

<img width="643" alt="CleanShot 2021-04-12 at 10 40 19@2x" src="https://user-images.githubusercontent.com/7003648/114422035-86378400-9b7b-11eb-9494-85fef9d20832.png">

However, the generated API key and secret should go in _consumer_ fields:

**Twitter developer**
![CleanShot 2021-04-12 at 10 41 00@2x](https://user-images.githubusercontent.com/7003648/114422327-c991f280-9b7b-11eb-8f28-1e286931468a.png)

**Yclas panel**
![CleanShot 2021-04-12 at 10 41 05@2x](https://user-images.githubusercontent.com/7003648/114422330-cac31f80-9b7b-11eb-8575-b2af8865e951.png)

And, the generated access token and secret  should go in _access_ fields:

**Twitter developer**
![CleanShot 2021-04-12 at 10 43 25@2x](https://user-images.githubusercontent.com/7003648/114422623-0d84f780-9b7c-11eb-80cd-e5886035f0ed.png)

**Yclas panel**
![CleanShot 2021-04-12 at 10 43 59@2x](https://user-images.githubusercontent.com/7003648/114422636-12e24200-9b7c-11eb-8ba1-cfcd9b8af10f.png)

Also, please make sure you set **Read and Write** permissions:

**Twitter developer**

![CleanShot 2021-04-12 at 10 46 00@2x](https://user-images.githubusercontent.com/7003648/114422911-4e7d0c00-9b7c-11eb-9a3a-88195770220e.png)

**Comment by neo22s** [comment]
then @jadecoyacot123 all its working correct?
