### ISSUE TITLE
Stripe connect express with escrow

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#3189]
https://stripe.com/docs/connect/express-accounts#prerequisites-for-using-express

This new feature request implements a simple type of escrow, using Stripe connect EXPRESS gateway
functionality This feature allows platform owners (PO) to charge a service fee for produces sold by
registered users (RU).

When a Registered Seller (RS) has registered with Stripe connect, a “buy now” button is shown on all his
/her ads. The onboarding of a stripe connect account is done via the RS Profile Page
=> everybody can post new ads without a stripe connect account!. In case the RS has NOT onboarded
with Stripe there is no ‘ buy now’ button on the single add, but a button ‘request safe payment’. In this
case email is send to RB which prompts him to register with Stripe connect EXPRESS.

Envisioned flow yclas
1. RU buys a product via “buy now’ button (and is directed to checkout .
2.The Registered Buyer (RB) pays at checkout via Stripe Connect with IDEAL
3.RS ships package and changes the status to “shipped” and the RB gets a notification.
4.RB receives the package and changes to status to “all is oke”,
5.When status is changed “all oke” , tYclas sends the payment instruction to Stripe to pay the RS
(the purchase price + shipping if any)-> https://stripe.com/docs/api#create_payout

Commission
6.using the panel set commision % + fix fee , also membership commission 

Cancellations
7. Cancellation of order: RS, RB must be able to cancel order always until the status is changed to ‘
‘Shipped’ by RS. PO must always be able to cancel an order anytime, even if its shipped in panel.
8. If the product is not set to ‘Shipped’ after a certain number of days [ USER INPUT], the
transaction is automatically cancelled, and RS and RB are informed.
9. A messages status change should be sent to RS “Canceled” and a message to RB ‘Refunding’.
PO panel payment flow – status changes
In yclas panel the PO should be able to monitor the transaction flow , and a button to cancel the
transaction.
10. Cancellations: In the panel, the PO must be able to follow the status of an order. If the status is ‘
Refunding’ the PO should be able change the status to ‘Refund Paid’ once the PO has paid therefund: this can be done with a button and stripe integration. The refund should be paid
automatically. A notification should be sent to relevant RB.
11. PO should also be able to set a transaction as “ received” ie “ completed” triggering the
automatic refund payment of RS. Refund is NET of stripe commission.

**Comment by neo22s** [comment]
@oliverds how do you see to add a tracking code when they mark an ad as shipped? new field in the table order? shipping_tracking_code?

**Comment by oliverds** [comment]
Sure, we can add a shipping tracking code. Also a shipping provider name? Include the tracking code on the order details? Not sure why it should be encrypted but it can be done.

**Comment by neo22s** [comment]
> Sure, we can add a shipping tracking code. Also a shipping provider name? Include the tracking code on the order details? Not sure why it should be encrypted but it can be done.

One customer wants to store domain name auth codes....

Shipping provider name it's good idea!!

**Comment by neo22s** [comment]
set to 30 days - Cancel orders not marketed as shipped after a certain number of days

**Comment by neo22s** [comment]
Option: Mandatory connect stripe. If not you can not post an ad

**Comment by neo22s** [comment]
Send email with tracking code and url.
