### ISSUE TITLE
Mollie implementation

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#3197]
Attached you find a ZIP with the folders and files for the [mollie_integration.zip](https://github.com/yclas/yclas/files/6370106/mollie_integration.zip)

- The oc/vendor/mollie-api-php folder holds the files from the Mollie API, including a lot of examples that you might want to delete before adding it to the core.

- I noticed that I created an empty button.php file. Not sure what button.php does with other payment modules.

- /themes/wtk/pages/ad/checkout.php holds a few lines for the Mollie button on checkout.
My theme is based on the Splash theme.

- An image from the Mollie logo is included in the default theme img folder.

- A new config setting is introduced: payment.mollie_api_key

**Comment by oliverds** [comment]
Guide: https://guides.yclas.com/#/Payment-set-up-payment-gateways?id=mollie

**Comment by neo22s** [comment]
great!!!
