### ISSUE TITLE
Comments still showing after disabled

### ISSUE THREAD

**Issue by jadecoyacot123** [yclas/yclas#3198]
When disabling the comment using the guides below, the comment section is still showing after creating a new add and ticking to disable it. 

http://guides.yclas.com/#/Custom-fields-publisher-to-enable-disable-comments

Comment disable is checked : 
![download - 2021-04-28T213612 358](https://user-images.githubusercontent.com/66590860/116413024-d005b700-a869-11eb-9706-4f368c4ee745.png)

But Disqus is still showing : 
![download - 2021-04-28T213616 992](https://user-images.githubusercontent.com/66590860/116413034-d300a780-a869-11eb-9d1b-31a91f9829ae.png)

**Comment by neo22s** [comment]
In which theme are you doing this?

**Comment by oliverds** [comment]
The "Publisher to enable/disable comments" feature only works if your using our [Disqus integration](https://guides.yclas.com/#/Publish-options-active-comments-with-disquse), but your are using Disqus directly in the HTML footer:

![CleanShot 2021-04-28 at 09 21 26@2x](https://user-images.githubusercontent.com/7003648/116419981-2c81bb80-a803-11eb-9fef-f365e79822ad.png)

**Comment by neo22s** [comment]
@jadecoyacot123 please be careful....

**Comment by jadecoyacot123** [comment]
yeah, I have replicated and it removed. I know the issue already. Should have removed that. All good. We can close this one for now.
