### ISSUE TITLE
Social Media Icon not showing on share widget

### ISSUE THREAD

**Issue by jadecoyacot123** [yclas/yclas#3199]
Share widget has been added already. The widget is showing, but not the icons added. 

![download - 2021-04-28T213917 926](https://user-images.githubusercontent.com/66590860/116413459-37bc0200-a86a-11eb-8a63-a358dea03529.png)
![download - 2021-04-28T213920 950](https://user-images.githubusercontent.com/66590860/116413470-3a1e5c00-a86a-11eb-8985-d6ed43d15be7.png)

**Comment by oliverds** [comment]
There's a typo on the guide. It should be "twitter": https://github.com/yclas/guides/commit/1c64394b9f7d14042947cecbd5e77ef83256cfe6#diff-9a039a0d5b176761f02eb1bdf92b3952e054e0c5a47a8bc3817f558e9392fa9dR9

**Comment by neo22s** [comment]
Thank!

**Comment by jadecoyacot123** [comment]
I changed it to twitter as motioned, still the icons doesnt show. Even with facebook and linkedin/.

**Comment by oliverds** [comment]
It looks ok to me. Please make sure you don't have enabled any AdBlock plugin.

http://akosibadak.tk:

<img width="1180" alt="CleanShot 2021-04-29 at 09 49 15@2x" src="https://user-images.githubusercontent.com/7003648/116570858-30c7da80-a8d0-11eb-8b2f-48ea4c70aee4.png">
