### ISSUE TITLE
Adding featured ads not working

### ISSUE THREAD

**Issue by jadecoyacot123** [yclas/yclas#3207]
When adding a featured plan, it just shows white page after clicking submit. and it goes to the URL : https://akosibadak.tk/oc-panel/settings/payment/update_featured_plan

Now, when refreshing the page. There is no added featured plans there. 

http://guides.yclas.com/#/Payment-featured-plans

**Comment by neo22s** [comment]
This happens only to you? I have tested in your site: 

https://akosibadak.tk/oc-panel/settings/payment

And works perfectly... disable any addblock please. 

![image](https://user-images.githubusercontent.com/241725/117407716-3a27f700-af0f-11eb-86cf-e893fe0d1b6f.png)
