### ISSUE TITLE
Improve one-click update reliability

### ISSUE THREAD

**Issue by oliverds** [yclas/yclas#3216]
It seems there is a persistent issue downloading the latest version prior "one-click" update process.

https://github.com/yclas/yclas/blob/master/oc/classes/controller/panel/update.php#L2781:
<img width="1390" alt="CleanShot 2021-05-18 at 10 14 50@2x" src="https://user-images.githubusercontent.com/7003648/118677540-ebf1de00-b7c1-11eb-9077-a327ae696d42.png">

Perhaps there is a follow redirection issue with the download url. Review `core::curl_get_contents` method.

**Comment by neo22s** [comment]
Some hostings have issues following the redirect.

Possible solution:

 if ( ($url_location = get_headers($download_url,1)) != FALSE AND is_array($url_location) AND isset($url_location['Location']) )
{      
       //d($url_location);
      $download_url = end($url_location['Location']);
      //d($download_url);
