### ISSUE TITLE
Upgrade instructions lack handling of custom css

### ISSUE THREAD

**Issue by JanKrohn-Khalibre** [yclas/yclas#3219]
Exception for custom css file should be made in upgrade documentation.
https://docs.yclas.com/how-to-update/

File that needs to be kept:
yclas-folder/themes/default/css/web-custom.css

If the file is deleted together with the rest of the installation, going to custom css configuration will throw an error message.

**Comment by neo22s** [comment]
Hello Jan,

That's correct it's missing, but those are the old docs, not sure where you get the link hehe, new one is:

https://guides.yclas.com/#/Yclas-self-hosted-installation-how-to-update?id=manual-update
