### ISSUE TITLE
Replace current or fix summernote

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#3232]
Got few complains because we use summernote and how it works. Find better alternative, light fast secure, open source.... xD

or fix the current integration heheh

**Comment by oliverds** [comment]
A few options:

- https://www.tiptap.dev (Personal preference 😄)
- https://prosemirror.net
- https://quilljs.com
- https://www.slatejs.org
- https://draftjs.org

Most of them are headless, so are not plug and play, they require custom setup and integration with yclas.

What are the biggest complaints about our current editor? So I can narrow the alternatives or improve the current integration.

We provide a very basic CMS for blog posts and pages so I think our current editor works ok.  Not the best, but ok. 😬

**Comment by neo22s** [comment]
We will review the summenote integration better

**Comment by oliverds** [comment]
Improved the Summernote embedded editor so it should have a better formatting.

**Comment by neo22s** [comment]
thanks oliver!!
