### ISSUE TITLE
Allowed domains not working properly

### ISSUE THREAD

**Issue by jadecoyacot123** [yclas/yclas#3236]
Hello,

The allowed domain field is not working properly. The domains added is still showing right after hitting enter. 

https://user-images.githubusercontent.com/66590860/120632630-c17b7280-c49b-11eb-8a19-b378ef3f661d.mp4

**Comment by oliverds** [comment]
Thanks for reporting it.

I have fixed the hint text, because it should be "Separate each domain with a comma."
