### ISSUE TITLE
Smartarget.online integration

### ISSUE THREAD

**Issue by neo22s** [yclas/yclas#3252]
New integration Smartarget.online
Creating a guide "how it works" Smartarget.online

attached the PDF
[yclas-smartarget.pdf](https://github.com/yclas/yclas/files/6719833/yclas-smartarget.pdf)

**Comment by oliverds** [comment]
Guide: https://guides.yclas.com/#/integrations-smartarget

**Comment by neo22s** [comment]
nice!!!! let's add it here too https://yclas.com/integrations.html thanks!

**Comment by oliverds** [comment]
Sure. It's now added to https://yclas.com/integrations.html and https://yclas.com/es/integraciones.html pages.

**Comment by neo22s** [comment]
Great! let upload to PRO!

thanks!

**Comment by neo22s** [comment]
Let's improve this:

 Once the user makes the integration, the code is also visible in the admin panel. The developers added it not just to the website, but also to the admin which can be very disturbing to your users. I would suggest adding the integration code just to the frontend of the website.
