### ISSUE TITLE
The vertical photo is lying on its side

### ISSUE THREAD

**Issue by wilsden** [yclas/yclas#3295]
When uploading a photo taken vertically from an iPhone 8 plus, the photo is loaded sideways see the photo
https://ibb.co/C9Yxq35

**Comment by neo22s** [comment]
Hello,

What's your website url?

**Comment by wilsden** [comment]
I deleted the site because the photos downloaded from the iPhone are loaded sideways on the site

**Comment by oliverds** [comment]
Hi,

We only accept issues that are bug reports. Bugs must be isolated and reproducible problems that we can fix within the Yclas core.

Make sure you are using PHP version 7.4+ and the latest imagick version.
