### ISSUE TITLE
Creating custom routes + views

### ISSUE THREAD

**Issue by Huanga-IT-Solutions** [yclas/yclas#3297]
Hello,

We're maintaining a barter platform for a customer based on the self hosted yclas. Our customer wants a custom route and a corresponding custom view with data from the backend. However, it seems that it's currently only possible to create static custom - pages in the OC - Panel.

Is there a way to create your own custom routes + views without the risk of overwriting edited yclas - files on updates? Are changes in the ycas - codebase required to fulfill this requirement? If so, we'd like to implement and commit this.. :) 

Thank you for your response!

**Comment by oliverds** [comment]
Hi,

We only accept issues that are bug reports. Bugs must be isolated and reproducible problems that we can fix within the Yclas core.

For your use case, you could fork Yclas and overwrite the routes files according to your needs.

**Comment by Huanga-IT-Solutions** [comment]
Could you tell me on which features you guys are currently working on? Mabye, if you're developing a similar feature as mentioned, we could contribute and submit a PR.
