### ISSUE TITLE
Self hosted version for commercial use

### ISSUE THREAD

**Issue by ugintl** [yclas/yclas#3299]
I want to use the self hosted version for a client. I saw the pricing. Do I have to pay if I use from Github? Can I buy templates?

**Comment by oliverds** [comment]
Yes, you can use Yclas Lite for commercial use (https://github.com/yclas/yclas/blob/master/LICENSE). You can also buy the PRO version and it includes 15 Pro templates.

[<img width="868" alt="CleanShot 2022-01-12 at 10 19 12@2x" src="https://user-images.githubusercontent.com/7003648/149179308-0f0db04a-e3bd-4f32-bff6-39d6f2bf8f44.png">](https://yclas.com/self-hosted.html)

**Comment by ugintl** [comment]
Is it the only difference between lite and pro? 15 templates?

**Comment by ugintl** [comment]
There are some open issues on github. What about them?

**Comment by oliverds** [comment]
Yup, we have open issues, but not sure what you mean.
