### ISSUE TITLE
Imagick is not installed 

### ISSUE THREAD

**Issue by sahaninduvara** [yclas/yclas#3304]
Can't upload any image to my site!!

Imagick is not installed, or the extension is not loaded [LOG]
![image](https://user-images.githubusercontent.com/62657643/149722637-22982311-853a-4397-b13e-a4b25b18c087.png)

**Comment by oliverds** [comment]
Hi,

We only accept issues that are bug reports. Bugs must be isolated and reproducible problems that we can fix within the Yclas core.

For your this error, it seems you don't have Imagick installed in your server.
